project:
  type: book
  preview:
    port: 4200
    browser: false

book:
  title: "L'Élégance de Bitcoin"
  output-file: main
  author: "Ludovic Lars"
  date: "01/31/2024"
  image: cover.png
  image-alt: "L'Élégance de Bitcoin"
  isbn: "978-9916-723-62-3"
  license: CC-BY-NC-SA-4.0
  language: fr
  publisher: Konsensus Network
  favicon: /figures/freestarfish.png
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    border: true
  navbar:
    left:
      - icon: book
        text: "Lire en ligne"
        href: index.qmd
        aria-label: Book
      - icon: shop
        text: "Acheter ce livre!"
        href: https://bitcoinbook.shop/products/lelegance-de-bitcoin
        aria-label: Shop
  page-footer:
    left:
      - text: "© 2024 Konsensus Network"
    center:
      - text: "License"
        href: index.qmd
      - text: "Acheter"
        href: presale.qmd
    right:
      - icon: twitter
        href: https://twitter.com/konsensusn
        aria-label: Twitter
      - icon: github
        href: https://github.com/konsensusnetwork
        aria-label: Github
      - icon: linkedin
        href: https://www.linkedin.com/konsensusnetwork
        aria-label: LinkedIn
      - icon: youtube
        href: https://www.youtube.com/konsensusnetwork
        aria-label: YouTube
  open-graph: true
  twitter-card:
    site: "@konsensusn"
  chapters:
    - index.qmd
    - chapters/preface-de-jacques-favier.qmd
    - chapters/remerciements.qmd
    - chapters/avant-propos.qmd
    - chapters/les-debuts-de-bitcoin.qmd
    - chapters/une-croissance-conflictuelle.qmd
    - chapters/des-racines-monetaires.qmd
    - chapters/la-necessite-de-decentralisation.qmd
    - chapters/un-mouvement-technologique.qmd
    - chapters/la-cybermonnaie-avant-nakamoto.qmd
    - chapters/la-valeur-de-l-information.qmd
    - chapters/le-consensus-par-le-minage.qmd
    - chapters/la-resistance-a-la-censure.qmd
    - chapters/le-changement-de-la-monnaie.qmd
    - chapters/la-determination-du-protocole.qmd
    - chapters/les-rouages-de-la-machine.qmd
    - chapters/les-contrats-autonomes.qmd
    - chapters/le-passage-a-l-echelle.qmd
    - chapters/l-avenir-de-bitcoin.qmd

format:
  html:
    lang: fr
    theme:
      light: [flatly, theme.scss, theme-light.scss]
    number-depth: 2
    grid:
      sidebar-width: 500px
      body-width: 900px
      margin-width: 350px
      gutter-width: 1em
    toc: true
    toc-location: left
    reference-location: margin
  epub:
    cover-image: cover.png
    cover-image-alt: |
      Book Cover
    creator: Konsensus Network
    toc: true
    toc-depth: 1
    toc-title: Inhoudsopgave
    lang: "nl-NL"
    css: epub.css
    number-depth: 2