# Avant-propos {#avant-propos .unnumbered}

Depuis sa conception en 2008 par Satoshi Nakamoto, Bitcoin a fait couler beaucoup d'encre. Au fil des années, il a suscité les plus grandes passions et il a été l'objet récurrent de débats enflammés. À son sujet, des milliers d'articles ont été écrits, des centaines de vidéos ont été tournées, et des dizaines de livres ont été publiés. La hausse de son prix lui a donné une visibilité extraordinaire dans les médias, à tel point qu'il s'est fait une place dans l'imaginaire collectif mondial.

Cependant, Bitcoin reste largement incompris. D'un côté, beaucoup de gens en parlent en n'ayant qu'une connaissance artificielle du sujet et ne parviennent pas à distinguer son utilité. Certains pensent qu'il ne sert qu'à spéculer, d'autres imaginent qu'il ne devrait être utilisé que par les criminels, d'autres encore vont jusqu'à dire qu'il ne s'agit que d'une pyramide de Ponzi. De l'autre côté, un certain nombre de personnes nourrissent des attentes démesurées, pensant qu'il pourrait devenir la monnaie de réserve mondiale, voire remplacer tous les échanges monétaires dans l'économie en quelques années seulement. Dans cette délusion, elles s'attachent à l'espoir que son prix atteigne des niveaux stratosphériques, dans la continuité des hausses spéculatives précédentes. Toutefois, peu de gens tentent d'adopter un point de vue réaliste et sobre, qui ferait la part des choses entre la vision des vendeurs de rêve pour qui Bitcoin serait la solution à tous les problèmes du monde, et les détracteurs de mauvaise foi pour qui Bitcoin représenterait un fléau à arrêter à tout prix.

J'ai personnellement entendu parler de Bitcoin pour la première fois en avril 2013, suite à la crise financière chypriote. Initialement assez sceptique, je me suis quand même intéressé à ce système, car celui-ci était mise en avant par les libéraux français et les libertariens américains que je suivais. Le 9 juillet 2015, j'ai essayé la chose : je me suis procuré 50 € de bitcoins (0,2 BTC) auprès de la plateforme d'achat-vente suisse Fastcoin (nommée aujourd'hui Bity) que j'ai reçus sur mon portefeuille Electrum nouvellement créé. J'ai réalisé ma première transaction sur la chaîne de Bitcoin dans la journée. Ces quelques fractions de bitcoin m'ont servi à faire des dons : d'abord au blogueur H16, puis à l'activiste Adam Kokesh, ensuite au projet DarkWallet de Amir Taaki et Cody Wilson, et enfin à la plateforme Sci-Hub gérée par Alexandra Elbakyan.

Mon implication dans Bitcoin n'a débuté réellement qu'au printemps 2017, lorsque le prix a recommencé à monter après des années de stagnation. Jusque-là, je m'étais contenté de suivre la cryptomonnaie de loin et cette hausse m'a intrigué. C'est à ce moment-là que je me suis pleinement plongé dans cet univers. J'ai lu à ce propos, notamment en me procurant des ouvrages comme *Bitcoin, la monnaie acéphale* d'Adli Takkal-Bataille et Jacques Favier, *Mastering Bitcoin* d'Andreas Antonopoulos ou encore *Digital Gold* de Nathaniel Popper. Je me suis également mis à spéculer à mon échelle en achetant du bitcoin, puis toutes sortes de cryptomonnaies alternatives.

En parallèle, j'ai commencé à écrire sur le sujet, si bien que je suis devenu rédacteur pour des sites spécialisés comme Cryptoast et le Journal du Coin. Au fil des années, j'ai rédigé plus de 150 articles de fond, sur divers sujets liés à la cryptomonnaie, que ce soit sous un angle technique, économique ou politique. Ma vision de Bitcoin a mûri en conséquence, de telle sorte que je pouvais prétendre « comprendre Bitcoin », même si ma conception restait évidemment parcellaire et influencée par ma propre perspective.

Cependant, ce n'était pas forcément le cas autour de moi, où les gens en avaient une idée superficielle, n'ayant probablement pas le temps de creuser davantage. C'est ce qui m'a poussé à écrire ce livre. En particulier, puisque le protocole monétaire dépendait des actions économiques de ses utilisateurs, il me paraissait important de partager la connaissance réelle qui avait émergé de mes recherches et de mon expérience. De plus, avec la progression de la censure bancaire, le développement des monnaies numériques de banque centrale, la guerre contre l'argent liquide et le retour de l'inflation, je pense qu'il est plus que jamais essentiel de bien appréhender cet outil afin de pouvoir l'utiliser correctement à l'avenir.

Cet ouvrage a pour but de présenter Bitcoin de manière claire et complète, en adoptant de multiples points de vue. Il narre le long cheminement qui a mené à sa création, ainsi que sa courte mais dense histoire, des origines à aujourd'hui. Il décrit son fonctionnement essentiellement économique découlant de sa nature monétaire. Il aborde les enjeux politiques auxquels Bitcoin répond, et en particulier le problème de la censure. Enfin, il examine ses rouages techniques de manière détaillée et précise. En lisant ce livre, vous finirez peut-être, comme moi, par voir en Bitcoin un ensemble harmonieux, dont le modèle de base est d'une rare élégance.

J'espère en tout cas que vous saurez apprécier cette modeste contribution à quelque chose qui nous dépasse : le projet d'une monnaie alternative, libre et résiliente, offrant aux simples individus la possibilité de résister aux puissances de ce monde. *Vires in numeris*.

::: flushright
Ludovic Lars, 1 décembre 2023
:::