# Des racines monétaires {#ch:monnaie}

[]{#enotezch:3 label="enotezch:3"}

[B]{.lettrine}[i]{.smallcaps}tcoin constitue un protocole de transfert de valeur qui gère l'émission et les échanges d'une unité de compte numérique du même nom, le bitcoin. Comme son nom l'indique (bitcoin est la fusion de *bit*, chiffre binaire, et de *coin*, pièce de monnaie), le bitcoin a vocation à être une monnaie. Il a ainsi été présenté comme tel dès ses débuts, comme l'atteste le titre du livre blanc qui en faisait « un système d'argent liquide électronique pair à pair ». C'est pourquoi il est nécessaire de comprendre l'économie et la monnaie afin de saisir correctement Bitcoin.

En particulier, le bitcoin est un nouvelle forme de monnaie. Il s'agit en effet d'une monnaie entièrement numérique qui se base sur un réseau décentralisé et qui ne nécessite pas d'autorité centrale pour fonctionner, ce qui constitue un véritable tour de force technique. Ce modèle original permet au bitcoin d'être résistant à la censure, dans le sens où il est difficile d'empêcher une transaction d'avoir lieu, et résistant à l'inflation, dans le sens où il est dur de créer de nouvelles unités. Grâce à cette proposition de valeur double, il représente une alternative viable au système monétaire et bancaire moderne.

Dans ce chapitre, nous nous proposons d'explorer les racines monétaires de Bitcoin, en expliquant d'abord ce qu'est la monnaie, en décrivant ensuite la conception qu'en a l'école autrichienne d'économie, avant de montrer en quoi le modèle du bitcoin est unique et où réside son utilité.

## Qu'est-ce que la monnaie ? {#quest-ce-que-la-monnaie .unnumbered}

La monnaie est un sujet ardu à appréhender et la conception que s'en font les gens est souvent floue et inexacte. Pourtant, il s'agit d'un instrument utilisé massivement dans nos sociétés modernes, caractérisées par la marchandisation et par la division du travail. Il est donc crucial d'appréhender cet objet de manière fine et pertinente.

L'importance concrète de la monnaie se retrouve dans la diversité des termes qui existent pour la désigner en français. D'abord, l'appelation la plus répandue pour parler de la monnaie est l'argent, si bien qu'on doit aujourd'hui préciser quand on veut parler du métal précieux. Ensuite, l'argot regorge de termes variés : le blé, en référence à la céréale ; l'oseille, désignant originellement une plante potagère ; le flouze, venant d'un mot arabe signifiant pièce de cuivre ; le pèze, qui viendrait peut-être du breton ; le pognon, qu'on échange de main à main ; la maille et le sou, qui sont les noms d'anciennes pièces de monnaie. Puis, pour sa forme liquide, on parle de numéraire ou d'espèces, ou bien de *cash*, un anglicisme venant de l'ancien français *casse*, qui a donné caisse. Enfin, il y a le mot « monnaie » lui-même, qui provient du latin *moneta*, issu du nom de temple de Juno Moneta (« Junon la Prévenante ») où se frappait la monnaie de Rome.

Une monnaie est un intermédiaire d'échange généralement accepté au sein d'un groupe de personnes donné. Il s'agit d'un outil utilisé dans l'échange indirect de biens et de services : une personne *vend* des biens et des services contre de la monnaie, qui lui sert ensuite à *acheter* d'autres biens et services.

La monnaie résout en cela le problème de la double coïncidence des besoins, qui se poserait dans une économie de troc où deux personnes doivent simultanément désirer le bien de l'autre dans la proportion souhaitée pour que l'échange puisse se faire d'une manière directe. Par exemple, si un boulanger souhaitait acquérir une pièce de viande contre quelques-unes de ses baguettes de pain, il devrait trouver un boucher désirant obtenir ces baguettes à cet endroit-là, à ce moment-là et pour ce montant-là. La monnaie est donc un bien intermédiaire que les gens acquièrent en vue de le céder contre autre chose, et qui fluidifie grandement leurs échanges.

Ce qui fait qu'un bien est utilisé comme monnaie plutôt qu'un autre, c'est ce qu'on appelle sa cessibilité[^128], c'est-à-dire la facilité avec laquelle ce bien peut être échangé sur le marché dès que son détenteur le désire et en encourant le moins de perte de valeur possible. Le bien servant de monnaie doit pouvoir être obtenu facilement sans que cela ne provoque une pénurie de monnaie. Cette propriété est similaire à la liquidité d'un marché, qui représente la capacité à acheter ou à vendre rapidement les biens qui y sont cotés sans que l'opération n'ait d'effet majeur sur les prix. C'est en ce sens qu'on décrit parfois la monnaie comme *le bien le plus liquide* au sein d'une économie donnée, et qu'on emploie le terme d'*argent liquide* en français pour parler de la monnaie physique composée des pièces et des billets, échangeables facilement et sans contrainte.

La monnaie n'est pas un concept dont les contours sont fixes et rigides. Un bien peut être plus ou moins une monnaie selon son niveau de cessibilité dans le groupe humain où il est échangé, de sorte qu'on peut parler de degré de monétarité ou de liquidité[^129]. L'or et le bitcoin disposent ainsi d'un degré de monétarité moindre que les devises étatiques en général, mais cela ne les empêche pas d'être considérés comme des monnaies au sens large. L'or est même mondialement perçu comme la réserve de valeur par excellence et comme le fondement historique de la monnaie, ce qui se retrouve dans la culture et en particulier dans les jeux vidéos.

De plus, la cessibilité d'un bien peut varier selon la situation. Le dollar n'est pas forcément utile en Europe où l'euro est bien plus cessible. L'or est un piètre instrument pour les paiements quotidiens, mais constitue une bonne manière de déplacer de la valeur dans le temps. Le bitcoin est peu utilisé dans le commerce physique, mais l'est beaucoup plus sur Internet. Les cigarettes ne servent pas de monnaie dans la population générale mais ont pu l'être dans certaines prisons. Le statut de monnaie dépend aussi du contexte.

La cessibilité élevée nécessaire pour que le bien soit sélectionné comme monnaie se retrouve dans les trois fonctions monétaires classiques, souvent citées par les économistes et dont l'origine est attribuée au philosophe Aristote. Ces fonctions de la monnaie sont les suivantes : premièrement, c'est un moyen de paiement, permettant de régler des échanges de manière directe ou différée (dette) ; deuxièmement, c'est une réserve de valeur, permettant d'épargner de la richesse pour l'utiliser plus tard ; troisièmement, c'est une unité de compte, servant de moyen standard d'exprimer la valeur des autres biens, sous la forme de prix. Autrement dit, la monnaie doit posséder une cessibilité qui s'adapte à la fois à l'espace, au temps et à l'échelle.

De ces trois *fonctions* fondamentales, on dérive usuellement les *qualités* essentielles de la monnaie, qui sont :

-   La portabilité : la monnaie doit être facilement transportable pour être transmise d'une personne à une autre, ou pour le dire autrement, le coût pour la déplacer doit être minimal ;

-   La durabilité : elle doit se conserver dans le temps, ne pas s'altérer, ne pas pourrir ;

-   La rareté : sa disponibilité doit être restreinte et ne pas être modifiée ;

-   La divisibilité : elle doit pouvoir être scindée en sous-parties plus petites ;

-   La fongibilité : chaque unité doit être interchangeable avec une autre ;

-   La vérifiabilité : la conformité de la monnaie doit pouvoir être vérifiée aisément et rapidement (les espèces doivent être « sonnantes et trébuchantes ») ;

-   La résistance à la censure : il doit être difficile d'empêcher une transaction de se faire (ce qui peut être remis en cause dans les solutions numériques) ;

-   L'historicité : la monnaie doit présenter une utilisation ancienne (et donc bénéficier de l'effet Lindy[^130]).

Ces qualités se sont retrouvées, de manière partielle ou totale, dans les différentes monnaies qui ont émergé et se sont imposées au cours de l'histoire.

## Les différentes monnaies {#les-différentes-monnaies .unnumbered}

On peut regrouper les monnaies qui ont existé en différentes catégories. Cinq formes plus ou moins distinctes se dégagent ainsi : la monnaie-marchandise, la monnaie représentative, le papier-monnaie, la monnaie-crédit et la monnaie numérique. Ces formes ont toutes des qualités singulières, qui sont le résultat de l'évolution monétaire mondiale.

Une monnaie-marchandise est, comme son nom l'indique, une marchandise qui est amenée à servir d'intermédiaire d'échange au sein d'un groupe donné. Une marchandise, dans le sens où nous l'entendons ici[^131], est un produit standardisé, essentiel et courant, dont les qualités sont parfaitement définies et connues des acheteurs, comme une matière minérale, un produit agricole ou un produit manufacturé. De ce fait, le bien utilisé possède originellement une utilité intrinsèque autre que monétaire : industrielle, alimentaire ou esthétique.

Les marchandises utilisées comme intermédiaire d'échange ont été nombreuses au cours de l'histoire de l'humanité. On a pu utiliser des restes d'animaux comme les coquillages et les ossements, des produits artisanaux comme les pagnes ou les couteaux, des denrées alimentaires comme le blé, les épices, les graines de cacao ou le sel[^132], des produits de l'élevage dont notamment le gros bétail, ou des matières naturelles comme les pierres ou les métaux.

Toutes ces marchandises possédaient de plus ou moins bonnes qualités monétaires, mais certaines souffraient de gros défauts, ce qui les rendaient moins adéquates à l'utilisation comme intermédiaire d'échange que d'autres. Le bétail avait une très mauvaise portabilité et n'était pas divisible. Les céréales comme le blé ou le riz étaient peu durables. La rareté des coquillages pouvait être élevée dans les terres, mais l'était peu près des côtes. Les produits artisanaux et les bijoux différaient légèrement les uns des autres ce qui nuisait à leur fongilibilité.

De manière générale, ce sont les métaux précieux, et tout particulièrement l'or, l'argent et le cuivre (sous forme de bronze), qui ont été sélectionnés au fil du temps pour finir par devenir la base monétaire mondiale. Cette convergence peut s'expliquer par le fait que ces trois métaux (de symboles chimiques respectifs Au, Ag et Cu) appartiennent tous les trois au groupe 11 de la classification périodique des éléments et qu'ils possèdent par conséquent des propriétés chimiques similaires, dont notamment une grande résistance à la corrosion et à l'oxydation, et une malléabilité élevée. L'utilisation de métaux multiples s'explique par leur portabilité imparfaite : l'or permet de déplacer beaucoup de valeur, mais n'est pas adapté aux petits paiements quotidiens, contrairement à l'argent et au cuivre.

Les métaux précieux ont pu être utilisés à l'état brut, sous la forme de lingots plus ou moins gros. Cependant, ils ont surtout été frappés sous la forme de pièces de monnaie, sur lesquelles une institution de confiance (généralement un État) inscrivait sa marque et certifiait le poids et la teneur en métal. Cette inscription constituait entre autres choses un certificat, intégré à la monnaie, qui avait pour but de faciliter l'échange par la non-nécessité de procéder à une vérification à chaque paiement.

Cette certification peut également être déconnectée de la monnaie, auquel cas on parle de monnaie représentative. Une monnaie représentative est une monnaie constituée de certificats, imprimés ou numériques, qui sont convertibles à vue contre une marchandise de base, comme de l'or ou de l'argent, auprès d'un tiers de confiance. L'aspect central d'une telle monnaie est qu'elle est théoriquement adossée à une réserve intégrale de monnaie de base, détenue par une ou plusieurs institutions. Les certificats sont par essence des substituts monétaires, c'est-à-dire des créances juridiquement exécutoires sur un débiteur pour un montant de monnaie de base déterminé.

L'archétype de la monnaie représentative est le système de l'étalon-or classique, qui était en vigueur durant la Belle Époque dans le monde occidental, où la monnaie était constituée de pièces d'or et de billets de banque convertibles en or. Cependant, avec le temps, la convertibilité a été progressivement abandonnée et les billets ont été transformés en une simple monnaie fiduciaire papier.

Une monnaie fiduciaire est une monnaie dont la valeur d'usage est négligeable par rapport à sa valeur nominale. La valeur initiale de la monnaie fiduciaire provient de la confiance (*fiducia* en latin) accordée à d'autres acteurs plutôt que de ses propriétés intrinsèques, comme c'est le cas des monnaies-marchandises. Cette confiance peut être placée dans un État, dans une firme ou bien dans une communauté. Elle se fonde non seulement sur la conviction que le dépositaire n'en dégradera pas les propriétés (dont notamment la rareté), mais aussi, dans le cas de l'État, sur l'assurance qu'il fera usage de la violence pour en contraindre l'utilisation, auquel cas on parle de monnaie fiat (du latin *fiat*, « qu'il soit fait », qui véhicule l'idée de décret). Contrairement à la monnaie représentative, la monnaie fiduciaire ne représente pas une marchandise ou une autre monnaie de base : *c'est* la monnaie de base.

L'exemple type de monnaie fiduciaire est le papier-monnaie, qui est une monnaie basée sur un support physique, dont la valeur d'usage est largement inférieure à la valeur nominale ou faciale indiquée sur le support. Le support peut être fabriqué à partir de papier, de tissu ou de plastique (billets) ou bien d'alliages de métaux composés par exemple de cuivre, de zinc et de nickel (pièces). Le maintien de sa valeur est garanti par la limitation de la production et la répression du faux-monnayage : sans cela, la monnaie deviendrait une monnaie-marchandise et la valeur d'échange des supports tendrait rapidement vers leur coût de production, généralement inférieur à leur valeur nominale.

Cette forme de monnaie a été expérimentée par les États à de multiples reprises au cours de l'histoire conduisant la plupart du temps à des inflations dramatiques, comme l'illustrent la tentative d'instauration d'une monnaie fiat par la dynastie Song entre le [xi]{.smallcaps} et le [xii]{.smallcaps} siècle en Chine ou l'épisode des assignats durant la Révolution française. Ce n'est que depuis le [xx]{.smallcaps} siècle et l'abandon de l'étalon-or que ce modèle s'est généralisé.

Une monnaie-crédit, aussi appelée monnaie scripturale, est une monnaie qui se rapporte à l'écriture (*scriptura* en latin) d'une dette dans un registre bancaire. Elle se distingue de la monnaie représentative par le fait qu'elle n'oblige pas le dépositaire à conserver le bien représenté en réserve. Les banques sont en effet des organismes de crédit, et pas des entrepôts de monnaie : lorsqu'une personne « dépose » des fonds sur un compte en banque, elle prêtent en réalité son argent à la banque qui « crédite » son compte en conséquence (d'où l'adage « les dépôts font les crédits »).

Tout comme la monnaie représentative, la monnaie-crédit est un substitut monétaire. La monnaie-crédit doit se fonder sur une unité de compte de base, issue d'une monnaie-marchandise (comme l'or) ou d'une monnaie fiduciaire (comme le dollar), qui sert à régler la dette lorsqu'elle arrive à échéance.

Aujourd'hui, le crédit est largement monétisé dans les sociétés occidentales, comme l'illustrent les moyens de paiement modernes que sont les chèques, les virements et les cartes bancaires. La monnaie scripturale compose plus de 90 % de la quantité en circulation de la monnaie au sens large.

Une monnaie numérique est une forme particulière de monnaie fiduciaire dont l'existence repose sur un registre géré informatiquement. Elle se distingue de la monnaie scripturale par le fait que l'entrée dans le registre n'est pas une créance en monnaie sur un tiers, mais *est la monnaie*. La monnaie est ainsi stockée sur une mémoire électronique, d'où le fait qu'on parle parfois de monnaie électronique[^133]. Une conséquence de la nature particulière de cette forme de monnaie est qu'elle est généralement programmable, dans le sens où on peut inscrire les conditions de dépense dans le système informatique qui la soutient.

Le premier exemple de monnaie numérique est celle qui est gérée de manière centralisée par une banque centrale. Elle constitue, avec les pièces et les billets, la base monétaire, qui est aussi appelée « monnaie de banque centrale » ou « monnaie centrale ». Plus précisément, il s'agit des avoirs monétaires détenus par les titulaires de comptes auprès de la banque centrale (c'est-à-dire des banques commerciales). Ce type de monnaie a permis de ne plus reposer uniquement sur des supports physiques, qui rendaient le règlement difficile et risqué. À l'avenir, la monnaie numérique étatique devrait être étendue à une monnaie numérique de banque centrale (MNBC) disponible pour les organismes financiers et, probablement, pour les particuliers.

Le second exemple de monnaie numérique est la cryptomonnaie, gérée de manière décentralisée par un réseau pair à pair, dont l'archétype est le bitcoin. Il s'agit d'une monnaie numérique de marché dans le sens où son existence n'est pas dépendante de l'intervention (ou de l'absence d'intervention) de l'État. C'est la monnaie sur laquelle se focalise cet ouvrage.

## L'école autrichienne et la valeur de la monnaie {#lécole-autrichienne-et-la-valeur-de-la-monnaie .unnumbered}

Puisque Bitcoin est un système monétaire, la compréhension de son fonctionnement et de ses enjeux passe par la connaissance de l'économie. Il existe de multiples manières d'aborder le sujet mais nous adoptons ici la perspective du courant économique dit « autrichien », qui est probablement la plus pertinente pour décrire Bitcoin, car elle a inspiré, au moins indirectement, sa création et son développement.

L'école autrichienne d'économie, parfois aussi appelée école de Vienne, est une école de pensée économique créée en Autriche au [xix]{.smallcaps} siècle autour de la figure de Carl Menger. Elle s'est initialement développée dans ce pays d'Europe centrale avec des penseurs comme Eugen von Böhm-Bawerk et Friedrich von Wieser. Après la Première Guerre mondiale et le démantèlement de l'Autriche-Hongrie en 1918, elle s'est exportée à l'étranger, dont notamment aux États-Unis, avec des économistes d'origine autrichienne comme Ludwig von Mises et Friedrich Hayek (ce dernier ayant reçu le prix « Nobel » d'économie en 1974). Par la suite, elle s'est étendue à des penseurs de toutes origines, dont les principales figures sont Murray Rothbard, Jesús Huerta de Soto et Hans-Hermann Hoppe.

L'école autrichienne se caractérise par son approche méthodologique -- l'individualisme méthodologique -- qui se fonde sur la praxéologie, c'est-à-dire l'étude rationnelle de l'action humaine. Cette méthode est aprioriste (ou axiomatique) dans le sens où elle repose sur un certain nombre d'axiomes qui ont trait au comportement humain. Elle part donc de la partie (l'individu) pour en déduire des conséquences logiques sur le tout (l'économie). L'école autrichienne s'oppose de ce fait aux écoles de pensée économiques qui se basent essentiellement sur l'observation et qui cherchent à modéliser « mathématiquement » l'économie, comme le néokeynésianisme, aujourd'hui majoritaire.

L'école autrichienne a en particulier une analyse fine de la valeur, c'est-à-dire l'intérêt ou l'importance qu'une personne porte à une chose.

Plusieurs conceptions de l'origine de la valeur existent. Certains considèrent que la valeur provient de la terre et de l'activité s'y rapportant, une thèse défendue par les économistes physiocrates du [xviii]{.smallcaps} siècle. D'autres postulent que la valeur tire son origine du travail, à l'instar d'Adam Smith, de David Ricardo, et surtout de Karl Marx, dont les partisans soutiennent cette théorie depuis le [xix]{.smallcaps} siècle.

L'école autrichienne d'économie diffère de ces conceptions en prônant une conception subjective de la valeur. Pour les autrichiens en effet, la valeur n'est pas un phénomène objectif et dépend du point de vue individuel. Selon Carl Menger :

« La valeur n'est pas inhérente aux biens, elle n'en est pas une propriété, elle n'est pas une chose qui existe en soi. C'est un jugement que les sujets économiques portent sur l'importance des biens dont ils peuvent disposer pour maintenir leur vie et leur bien-être. Il en résulte que la valeur n'existe pas en dehors de la conscience des hommes[^134]. »

Ainsi, un individu peut accorder une immense grande valeur à un bien (un tableau par exemple) tandis qu'un autre ne lui en accordera aucune. De même, la valeur prodiguée peut varier selon le contexte : une personne vivant dans le désert ne portera pas le même intérêt à un litre d'eau que quelqu'un résidant dans une région humide.

La valeur d'un même bien peut être différente aux yeux d'un individu selon sa consommation antérieure. S'il est affamé, il accordera une grande valeur à une pomme ; mais à mesure qu'il se sustentera, la valeur qu'il donnera aux pommes suivantes décroîtra. C'est ce qu'on appelle l'utilité marginale.

La valeur que l'individu tire d'un bien est appelée la « valeur d'usage » par les économistes. Le sens porté à ce terme est différent selon les personnes qui l'utilisent. Ainsi, il renvoie souvent à la valeur d'usage objective, qui est la relation entre une chose et l'effet qu'elle a la capacité d'entraîner, comme par exemple le pouvoir de chauffage du bois. Mais le terme peut également, dans le contexte autrichien, faire référence à la valeur d'usage subjective, qui n'est pas toujours fondée sur un critère objectif d'évaluation.

L'estimation de la valeur des biens et des services permet à l'individu de savoir comment orienter sa production et sa consommation. Mais cette appréciation intervient également dans le commerce : un échange a lieu seulement si les deux parties de cet échange donnent *plus de valeur* au bien économique possédé par autrui. De ce fait, si un bien appartenant à autrui vaut pour moi plus que quatre pièces d'argent et que cette autre personne accorde plus de valeur à deux pièces d'argent qu'à ce bien, alors un échange à un prix de trois pièces d'argent sera bénéfique pour nous deux. C'est pour cette raison qu'à long terme le marché libre *crée* de la richesse. Le prix ainsi obtenu dans le commerce est parfois appelé « valeur d'échange ».

Même si la valeur est subjective, cela n'empêche pas les êtres humains d'accorder de la valeur aux mêmes choses. D'abord, en tant qu'ils sont semblables, ils valorisent naturellement les biens qui leur permettent de satisfaire leurs besoins physiologiques primaires (eau potable, nourriture, vêtements, abris, etc.). Ensuite, ils ont tendance à copier le désir d'autrui pour des choses non nécessaires, conformément à la nature mimétique du désir, ce qui a pour effet de créer les engouements et les effets de mode autour d'objets communs. Enfin, ils accordent de la valeur aux biens d'ordre supérieur, que ce soient des outils (capital) ou des matières premières, qui permettent de fabriquer les biens de consommation désirés.

La monnaie est un cas particulier dans l'analyse de la valeur. Elle repose sur un phénomène intersubjectif : une construction psychologique qui se fait au sein de chaque personne et qui se renforce à mesure qu'elle s'enracine dans l'esprit des autres. Chacun acquiert de la monnaie parce qu'il pense qu'il pourra l'échanger contre un autre bien plus tard, ce qui affermit la conviction des autres que la monnaie peut effectivement être utilisée. C'est un cercle vertueux conforme à l'effet de réseau.

De ce fait, même si la valeur est évaluée subjectivement, la valeur de la monnaie converge nécessairement vers une valeur d'échange objective commune à tous, qu'on appelle le pouvoir d'achat. Ce pouvoir d'achat peut varier selon la période et selon la localité, au gré des variations naturelles du marché et des distorsions causées par l'État. Lorsqu'il baisse durablement (ce qui se manifeste par une augmentation généralisée des prix), on parle d'inflation. Lorsqu'il augmente durablement (ce qui se traduit par une baisse généralisée des prix), on parle de déflation.

Au sein de la valorisation du bien utilisé comme monnaie, il est donc possible de distinguer deux valeurs mutuellement exclusives : sa valeur non monétaire, c'est-à-dire l'utilité alimentaire, industrielle, esthétique, etc. que la personne en retire ; et sa valeur strictement monétaire, qui découle de l'avantage provenant de l'utilisation du bien comme intermédiaire d'échange. Pour les monnaies-marchandises par exemple, on peut distinguer la demande dite « intrinsèque » de la demande monétaire : l'or ne tire pas sa valeur uniquement de sa demande esthétique (bijoux) et industrielle (microprocesseurs), mais aussi, et surtout, de sa demande en tant qu'intermédiaire d'échange, qui provient notamment des banques centrales.

Les économistes autrichiens minimisent le rôle de l'État dans la création de la monnaie, postulant qu'elle a largement émergé de l'échange économique, du moins en ce qui concerne sa forme la plus primitive. Ils s'opposent en cela aux chartalistes et aux partisans de la théorie monétaire moderne, qui affirment que la monnaie est née de l'intervention étatique et que sa valeur provient de son emploi pour le paiement l'impôt[^135]. Tel que l'écrivait Carl Menger :

« L'origine de la monnaie (qu'il faut distinguer des pièces de monnaie, qui n'en sont qu'une variété) est \[\...\] tout à fait naturelle, et elle n'est donc qu'en de très rares circonstances le résultat d'une influence de la législation. La monnaie n'est ni une invention de l'État, ni le produit d'un acte législatif, et la sanction d'un tel acte par l'autorité de l'État est donc étrangère à la notion même de monnaie[^136]. »

Dans cette perspective, la monnaie tire son origine de l'échange entre les groupes d'individus qui ne se faisaient pas confiance, mais qui étaient désireux de coopérer. Ainsi les protomonnaies (ou paléomonnaies) ont émergé, non pas au sein des tribus humaines, dont le fonctionnement interne reposait largement sur le don et le crédit, mais *entre* ces tribus. Cela pouvait concerner l'échange simple de marchandises, la résolution de conflits, le règlement de mariages et le paiement de tributs[^137].

Avec la mondialisation progressive de la planète, les protomonnaies ont subi une sélection : beaucoup d'entre elles ont disparu au profit de celles qui satisfaisaient les propriétés d'une bonne monnaie. En particulier, le bien sélectionné devait être facile à cacher (résistance à la censure), difficile à produire (rareté) et sa valeur devait pouvoir être aisément approximée (vérifiabilité). La monnaie a convergé vers les pièces de métal précieux, le plus souvent d'or et d'argent, de préférence frappées par une autorité reconnue. Les premières pièces frappées sont vraisemblablement apparues au [vii]{.smallcaps} siècle avant Jésus-Christ en Asie Mineure sous l'impulsion des Lydiens, et étaient constituées d'électrum, un alliage naturel d'or et d'argent. Par la suite, de nombreuses pièces différentes se sont succédées : la darique perse, la drachme grecque, le denarius romain, le solidus byzantin (besant), etc.

L'utilisation de pièces s'est faite pendant des siècles et s'est généralisée à la planète entière. Néanmoins, cet usage a progressivement reculé à partir de la Renaissance avec l'émergence des billets de banque, qui se sont généralisés au cours du [xix]{.smallcaps} siècle grâce à l'action des États. Le passage au papier-monnaie fiduciaire a eu lieu durant le [xx]{.smallcaps} siècle avec l'abandon total de toute référence aux métaux précieux dans le système monétaire en 1971. Nous avons assisté à une véritable corruption de la monnaie, qui a apporté quelques bénéfices mais qui a surtout permis aux autorités de davantage profiter de la création monétaire par le biais de la fameuse « planche à billets ».

Pour les partisans de la liberté, il est crucial de procéder à une rédemption de la monnaie[^138], en revenant à ce que les économistes autrichiens appellent une monnaie saine. Une monnaie saine est une monnaie librement choisie par le marché qui reste à l'abri des ingérences coercitives. Tel que l'écrivait Ludwig von Mises dans sa *Théorie de la monnaie et du crédit* en 1912 :

« Le principe de la monnaie saine comporte deux aspects. Il est positif en ce qu'il approuve le choix par le marché d'un intermédiaire d'échange couramment utilisé. Il est négatif en ce qu'il fait obstacle à la propension du gouvernement à s'immiscer dans le système monétaire[^139]. »

Plusieurs projets politiques ont émergé dans le but de rétablir un système monétaire mondial basé sur une monnaie saine. Le premier était celui de Mises (et de Rothbard) visant à restaurer l'étalon-or. En effet, pour Mises, « une monnaie saine signifie un étalon métallique » et l'étalon-or « rend la détermination du pouvoir d'achat de l'unité monétaire indépendante des États et des partis politiques ».

Le second projet était celui de Friedrich Hayek, développé plus tard, qui prônait une concurrence de monnaies (représentatives ou fiduciaires) qui seraient émises par des banques privées[^140]. Cela a inspiré le modèle de la banque libre, dans lequel les organismes financiers pourraient agir librement sans intervention d'une banque centrale ou d'une autre instance, un modèle notamment soutenu par les économistes Lawrence White, George Selgin et Kevin Dowd.

Aucun de ces deux projets politiques n'a jamais abouti, malgré des décennies d'évènements démontrant la validité des thèses autrichiennes. Comme l'a montré l'histoire, le contrôle étatique sur la monnaie s'est progressivement étendu jusqu'à devenir ce qu'il est aujourd'hui, un contrôle tendant vers le totalitarisme. Cependant, il existe une alternative, une solution non pas politique, mais économique : Bitcoin.

## Une nouvelle forme de monnaie {#une-nouvelle-forme-de-monnaie .unnumbered}

Si l'on parle autant de Bitcoin, c'est qu'il apporte quelque chose de nouveau, non seulement d'un point de vue technique, mais aussi et surtout dans une perspective économique. La découverte de ce système par Satoshi Nakamoto en 2008 représente en effet un véritable bouleversement dans le domaine monétaire. Le bitcoin constitue une forme de monnaie inédite : une monnaie *sui generis* (pour reprendre l'expression de Jacques Favier), de son propre genre, qu'il est difficile de placer dans les cases existantes.

Premièrement, il s'agit comme on l'a évoqué d'une monnaie entièrement numérique. Le bitcoin se base sur un registre de propriété public (la chaîne de blocs) qui définit la monnaie : les entrées de ce registre ne correspondent pas à des créances, comme c'est le cas pour la monnaie-crédit, mais à la monnaie elle-même.

Deuxièmement, cette monnaie numérique innove par le fait qu'elle ne nécessite pas de tiers de confiance pour fonctionner. Le contenu du registre ne dépend pas d'une institution financière comme une banque centrale, mais d'un ensemble d'acteurs agissant par le biais d'un réseau distribué d'ordinateurs.

Troisièmement, sa sécurité est assurée de manière économique : elle ne repose pas sur un bénévolat altruiste (même s'il joue évidemment un rôle), mais sur les incitations économiques des différents acteurs impliqués. Cela donne au système une stabilité à long terme dont n'ont jamais disposé les différentes monnaies privées qui l'ont précédé.

Ces propriétés permettent au bitcoin de constituer une monnaie fiduciaire distribuée, dans le sens où il ne possède pas d'utilisation non monétaire significative et où sa valeur provient de la confiance accordée à une économie de commerçants plutôt qu'à un tiers. On peut également le qualifier de monnaie réticulaire (du latin *reticulum*, « filet à petites mailles », « réseau ») dans la mesure où la confiance est répartie sur le réseau des nœuds des commerçants plutôt qu'être concentrée sur un serveur central.

Bien que le bitcoin semble se rapprocher par ses caractéristiques des monnaies-marchandises[^141], il ne s'agit aucunement d'une marchandise. Les propriétés de Bitcoin émergent d'un accord atteint par l'ensemble de ses utilisateurs, pas de caractéristiques intrinsèques du monde physique comme c'est le cas pour l'or ou l'argent. Il est ainsi possible de modifier les règles de consensus du système, même si un tel changement est très difficile.

En réalité, une monnaie est toujours un accord concernant un intermédiaire mutuellement acceptable dans le commerce. Dans le cas de la monnaie-marchandise, cet accord converge naturellement vers une denrée qui est déjà échangée au sein de la société. Dans le cas de la monnaie fiat, l'agrément est maintenu par un décret étatique disposant du respect de la population. Dans le cas de Bitcoin, la coordination est réalisée de manière volontaire autour de règles de consensus spécifiques.

C'est l'étendue de cet accord qui donne sa force à la monnaie, par effet de réseau : son utilité augmente en effet de manière superlinéaire par rapport à la taille de l'économie l'utilisant. C'est ce qui fait qu'une monnaie peut difficilement être remplacée par une autre, et c'est aussi ce qui rend difficile l'altération des règles de consensus du système, comme nous le verrons dans le chapitre [11](#ch:determination){reference-type="ref" reference="ch:determination"} sur la détermination du protocole.

L'avantage premier de la monnaie-marchandise n'est pas de disposer d'une valeur intrinsèque, mais d'exiger un coût infalsifiable pour sa production, de façon à éviter qu'une création monétaire excessive ne détruise son pouvoir d'achat. En effet, dans le cas d'une monnaie fiduciaire étatique ou privée, la détermination de la monnaie se trouve entièrement entre les mains de l'émetteur, qui peut bénéficier de la situation en créant plus d'unités à son avantage, surtout s'il jouit d'un privilège légal.

Bitcoin est différent et n'est pas soumis à un tel risque : son fonctionnement distribué répartit sa détermination dans l'économie et l'empêche d'être soumis à l'arbitraire d'un tiers. Cette particularité lui permet de disposer d'une caractéristique inédite : une rareté absolue, découlant d'une quantité fixe d'unités émises selon un programme prédéfini. C'est d'ailleurs l'un des facteurs qui ont construit sa renommée : le fait que l'offre monétaire soit limitée à 21 millions de bitcoins.

La « valeur intrinsèque » n'est donc pas un élément essentiel à la qualité de la monnaie. Le bitcoin, qui est une forme pure de monnaie, valorisée quasi exclusivement pour son rôle de monnaie, en est la preuve. Avec les monnaies-marchandises, les propriétés physiques de la monnaie constituaient un garde-fou contre les interventions privées et étatiques ; dans Bitcoin, c'est le réseau qui possède cette fonction.

## Bitcoin et le théorème de régression {#bitcoin-et-le-théorème-de-régression .unnumbered}

Certains économistes autrichiens refusent d'admettre que le bitcoin ait pu émerger sans avoir de valeur d'usage objective. Ils font pour cela référence au théorème de régression de Ludwig von Mises, qui stipule que la valeur d'échange de la monnaie est calculée par rapport à sa valeur précédente et doit, par régression, être ramenée à sa valeur en tant que marchandise.

L'essentiel de ce théorème se trouve dans la *Théorie de la monnaie et du crédit*, un ouvrage publié en 1912, où Mises écrit :

« La théorie de la valeur de la monnaie en tant que telle peut faire remonter la valeur d'échange objective seulement jusqu'au point où elle cesse d'être la valeur de la monnaie et devient uniquement la valeur d'une marchandise. À ce point, la théorie doit laisser cours pour toute investigation ultérieure à la théorie générale de la valeur, qui n'a alors plus aucune difficulté à résoudre le problème. Il est vrai que l'évaluation subjective de la monnaie présuppose une valeur d'échange objective existante, mais la valeur qui a besoin d'être présupposée n'est pas la même que la valeur qu'il faut expliquer. Ce qui est présupposé est la valeur d'échange d'*hier* et il est parfaitement légitime de l'utiliser pour expliquer celle d'aujourd'hui. La valeur d'échange objective de la monnaie qui s'établit sur le marché d'aujourd'hui découle de celle d'hier sous l'influence des évaluations subjectives des individus fréquentant le marché, tout comme celle d'hier découlait à son tour, sous l'influence des évaluations subjectives, de la valeur d'échange objective de la monnaie d'avant-hier. Si de cette façon nous retournons de façon continuelle en arrière, nous devons arriver à un point où nous ne trouvons plus aucune composante dans la valeur d'échange objective qui provienne des évaluations basées sur la fonction de la monnaie comme moyen d'échange commun ; un point où la valeur de la monnaie n'est rien d'autre que la valeur de l'objet qui est utile d'une autre façon que comme monnaie[^142]. »

Le théorème comporte deux éléments : la régression et la première valorisation.

Concernant la régression, le raisonnement se tient : la valeur attribuée à la monnaie se base sur sa valeur précédente, de sorte qu'on peut remonter à une valeur entièrement non monétaire. Il n'y a pas besoin que cette première valeur se maintienne : une fois que la monnaie a été établie, sa valorisation peut reposer uniquement sur la mémoire des prix précédents.

Cette régression se vérifie historiquement. La valeur de nos billets fiduciaires actuels en Occident peut être retracée de proche en proche jusqu'à la valeur des billets en tant certificats or, qui est issue de la valeur des pièces de monnaies, qui provient elle-même de la valeur de l'or sous forme brute. Cet or a été valorisé premièrement pour des motifs ornementaux et religieux avant de commencer à servir d'intermédiaire d'échange.

Concernant la première valorisation, ce qu'affirme Ludwig von Mises est plus inexact. Il parle d'une « marchandise » (*commodity* en anglais, *Ware* en allemand) qui est initialement valorisée pour son utilité « industrielle[^143] » (*industrial* en anglais, *industriell* en allemand), donc d'un produit standardisé et courant dont les qualités sont définies et connues. À un autre endroit, il s'oppose explicitement à la théorie lockéenne de l'origine de la monnaie qui, selon ses termes, fait « découler l'origine de la monnaie d'un accord général qui aurait attribué des valeurs fictives à des choses intrinsèquement sans valeur[^144] ». Il semble ainsi que Mises exclut qu'un bien intangible sans valeur d'usage objective puisse devenir un intermédiaire d'échange sans être adossé à une monnaie précédente.

Pourtant c'est exactement ce qui s'est passé avec le bitcoin, dont le succès constitue un contre-exemple limpide au théorème de régression dans son acception la plus stricte. L'erreur de Mises semble venir de son biais en faveur des métaux précieux lié à la période durant laquelle il écrivait, c'est-à-dire le début du [xx]{.smallcaps} siècle. Il était en effet difficile d'imaginer un système monétaire aussi fantaisiste que Bitcoin, des décennies avant la révolution technique de l'ordinateur personnel et d'Internet. Comme l'expliquait Satoshi Nakamoto en août 2010 :

« Je pense que les critères traditionnels de la monnaie ont été décrits en partant du principe qu'il y avait tellement d'objets rares en concurrence dans le monde, qu'un objet bénéficiant de l'amorce automatique d'une valeur intrinsèque l'emporterait sûrement sur ceux sans valeur intrinsèque. Mais s'il n'y avait dans le monde rien qui ait de valeur intrinsèque et qui puisse être utilisé comme monnaie, s'il y avait seulement des objets rares mais sans valeur intrinsèque, je pense que les gens opteraient quand même pour quelque chose[^145]. »

Toutefois, malgré cette conception erronée, le théorème de régression reste valide dans une acception plus large. Pour pouvoir servir d'intermédiaire d'échange, toute monnaie a dû *nécessairement* posséder en premier lieu une valeur d'usage non monétaire. Il a par conséquent fallu que quelqu'un donne une valeur au bitcoin « pour une raison ou pour une autre[^146] » avant qu'une utilisation monétaire, comme par exemple « transférer de la richesse sur une longue distance », devienne possible.

Il existait donc un problème d'amorçage. Le cryptographe Hal Finney, qui avait expérimenté les systèmes d'argent liquide numérique au début des années 1990, en était notamment conscient. Dès les débuts de Bitcoin en janvier 2009, il écrivait :

« Un des problèmes immédiats avec n'importe quelle nouvelle monnaie est de savoir comment la valoriser. Même en ignorant le problème pratique lié au fait que quasiment personne ne l'acceptera au début, il est toujours difficile de trouver un argument raisonnable en faveur d'une valeur particulière non nulle pour les pièces[^147]. »

Mais cet amorçage a fini par avoir lieu.

## L'émergence de la valeur du bitcoin {#lémergence-de-la-valeur-du-bitcoin .unnumbered}

Selon le théorème de régression, le bitcoin a dû posséder une valeur d'usage non monétaire (objective ou subjective) avant d'être valorisé en tant qu'intermédiaire d'échange. Au cours des années, différentes hypothèses de première valorisation ont été proposées pour expliquer l'émergence de la valeur du bitcoin sur le marché. Examinons-en les principales, en commençant par les moins plausibles pour finir par les plus vraisemblables.

Tout d'abord, une hypothèse malheureusement trop souvent citée est la valeur qui découlerait de l'énergie utilisée pour sa production. Cette hypothèse provient notamment sur l'estimation de NewLibertyStandard, qui, à partir d'octobre 2009, vendait et achetait des bitcoins à un taux basé sur le coût énergétique de sa production personnelle. Il s'agit essentiellement d'une version revisitée de la théorie de la valeur-travail des marxistes. Cette explication était déjà critiquée par Satoshi Nakamoto en février 2010, qui écrivait que le coût de production était une conséquence du prix, et non pas une cause :

« En l'absence d'un marché pour établir le prix, l'estimation de NewLibertyStandard basée sur le coût de production est une bonne estimation et un service utile (merci). Le prix de toute marchandise tend à graviter vers le coût de production. Si le prix est inférieur au coût, alors la production ralentit. Si le prix est supérieur au coût, il est possible de réaliser des bénéfices en produisant et en vendant davantage. Dans le même temps, l'augmentation de la production accroîtrait la difficulté, poussant le coût de production vers le prix[^148]. »

Certaines personnes ont également suggéré que la valeur proviendrait du fait que le bitcoin a été échangé contre du dollar, avançant l'idée que la régression se transmettrait avec cette conversion. Cependant, le change avec le dollar a toujours été réalisé à taux variable, selon l'offre et la demande, sans aucune entité pour garantir un taux fixe. De ce fait, cette hypothèse ne peut pas être valide.

Une autre hypothèse de première valorisation évoquée est celle qui ferait résider la valeur initiale du bitcoin dans sa capacité à être un système de paiement. Mais cet argument doit être écarté car il est circulaire : nul ne peut payer en bitcoins si ce dernier n'a de valeur pour personne. De plus, même si le réseau avait permis de traiter des transferts en dollars ou en euros, les paiements réalisés n'auraient pas été sécurisés du tout, en raison du caractère économique de la sécurité minière de Bitcoin, que nous décrirons dans le chapitre [8](#ch:confirmation){reference-type="ref" reference="ch:confirmation"}.

Une hypothèse apparentée est que des individus auraient attribué de la valeur au bitcoin pour sa capacité à servir pour l'horodatage, c'est-à-dire l'association d'une date et d'une heure à une information spécifique. Bitcoin permet en effet d'écrire des données arbitraires sur sa chaîne de blocs, ce qui garantit leur authenticité notariale, et on peut par exemple publier l'empreinte d'un document dans une transaction pour montrer que ce document existait antérieurement à la date de confirmation de la transaction. Néanmoins, pour que cet ancrage sur la chaîne possède une quelconque utilité, il faut qu'il soit difficile de modifier le registre. Puisque la sécurité de Bitcoin est essentiellement économique, cet usage ne peut donc pas avoir permis de première valorisation. De plus, cela ne s'est pas passé d'une telle manière : si on met de côté le message contenu dans le premier bloc (ayant pour but d'empêcher l'antidatage du lancement), aucune donnée arbitraire n'a été inscrite sur la chaîne avant 2011.

S'il faut chercher des raisons à la première valorisation du bitcoin, on doit les trouver dans les préférences strictement subjectives de l'individu, non pas dans une hypothétique valeur d'usage objective. Au vu de l'histoire de Bitcoin durant ses premières années d'existence, on peut observer qu'il a existé deux raisons principales derrière une telle valorisation : la dimension culturelle et l'aspect spéculatif.

La première raison derrière la valorisation initiale est la motivation culturelle. Selon cette hypothèse, le bitcoin a été un collectionnable, représentant les principes en lesquels croyaient les individus qui lui ont porté de l'intérêt. C'est ce qui a poussé les gens à s'en procurer alors même qu'ils n'en avaient aucun avantage matériel à en retirer. Cela rejoint en un sens l'idée de valorisation en tant que système de paiement, à une nuance près : l'individu ne donne de la valeur au bitcoin parce que le système est un bon système de paiement à un instant précis, mais parce qu'il souhaite que ce projet réussisse.

Dans cette logique, l'économiste autrichien Konrad S. Graf parlait en 2013 de « composantes de la valeur de consommation directe » qui seraient « psychologiques ou sociologiques dans le sens où elles se rapportent à des facteurs tels que l'attrait inhérent pour les geeks, le défi professionnel lancé aux spécialistes, la curiosité et le signal d'appartenance[^149] ». Dans le même ordre d'idées, Ross Ulbricht, le créateur de la place de marché Silk Road, expliquait dans un essai rédigé en 2019 :

« C'est comme par magie que le bitcoin a pu en quelque sorte provenir de rien et, sans valeur préalable ni décret autoritaire, devenir une monnaie. Mais Bitcoin n'a pas émergé du vide. C'était la solution d'un problème sur lequel les cryptographes buttaient depuis de nombreuses années : Comment créer une monnaie numérique sans autorité centrale qui ne puisse pas être contrefaite et qui soit digne de confiance.

Ce problème a persisté si longtemps que certains ont laissé sa résolution aux autres et ont rêvé à la place de ce que serait notre avenir si la monnaie numérique décentralisée devenait réalité d'une manière ou d'une autre. Ils rêvaient d'un avenir où le pouvoir économique du monde serait accessible à tous, où la valeur pourrait être transférée n'importe où en appuyant sur un bouton. Ils rêvaient de prospérité et de liberté, qui ne dépendraient uniquement que des mathématiques du chiffrement fort[^150]. »

C'est donc le rêve d'une monnaie numérique libre qui a en partie motivé la valorisation initiale du bitcoin. L'objectif était, dès le début, de créer une monnaie, et le bitcoin a été valorisé pour cette propension.

Bitcoin était notamment conforme à l'idéal libertarien étasunien, représenté à l'époque par l'homme politique Ron Paul, qui proposait notamment d'« abolir la Fed » et qui a brigué l'investiture républicaine pour l'élection présidentielle de 2008 puis celle de 2012. Les cypherpunks, majoritairement originaires des États-Unis, se rapprochaient largement de cette idéologie. Satoshi lui-même était conscient de cette proximité, déclarant dès novembre 2008 que le concept de Bitcoin était « très attrayant du point de vue libertarien[^151] ». C'est donc tout naturellement que les premières personnes à apporter de la valeur au bitcoin ont été ces libertariens, à l'instar de Martti Malmi, de NewLibertyStandard ou, plus tard, de Ross Ulbricht.

La deuxième raison derrière la première valorisation du bitcoin est la valeur spéculative qui provenait de sa potentielle utilisation en tant que monnaie. La promesse de Bitcoin faisait qu'il pouvait être intelligent de parier là-dessus. En particulier, le bitcoin devait devenir au fil du temps une monnaie à quantité fixe (21 millions), dont la rareté était absolue.

Cette caractéristique unique a bouleversé l'imagination des gens. S'il y avait un nombre limité de bitcoins et que l'utilité monétaire du réseau augmentait, alors leur prix unitaire subirait théoriquement une forte hausse. C'est sur quoi se sont basées les engouements spéculatifs successifs qui ont jalonné l'histoire de la cryptomonnaie.

Cette idée est apparue en janvier 2009, lorsque Hal Finney a estimé dans un courriel que le prix unitaire du bitcoin pourrait atteindre la coquette somme de 10 millions de dollars :

« Comme expérience de pensée amusante, imaginez que Bitcoin réussisse et devienne le système de paiement dominant utilisé dans le monde entier. Alors, la valeur totale de la devise devrait être égale à la valeur totale de toutes les richesses du monde. Les estimations actuelles que j'ai trouvées de la richesse totale des ménages dans le monde varient de 100 à 300 milliards de dollars. Avec 20 millions de pièces, cela donne à chaque pièce une valeur d'environ 10 millions[^152]. »

Cette estimation était plus que contestable (la monnaie n'est pas censée représenter toute la richesse du monde), mais elle portait en elle la notion que chacun pouvait profiter de la hausse du cours.

Par la suite, Satoshi a lui-même utilisé cette logique pour attirer les utilisateurs potentiels. Il déclarait ainsi le 16 janvier qu'« il pourrait être judicieux d'en avoir au cas où cela prendrait » et que « si suffisamment de gens \[pensaient\] la même chose, cela \[deviendrait\] une prophétie autoréalisatrice[^153] ». Le 18 février, il écrivait qu'« à mesure que le nombre d'utilisateurs \[croissait\], la valeur par pièce \[augmenterait\] » ce qui constituerait une « boucle de rétroaction positive[^154] » pour le système.

Ainsi, ce sont ces deux raisons -- culturelle et spéculative -- qui ont principalement contribué à la première valorisation du bitcoin. Si les premiers mineurs ont daigné utiliser leur ordinateur et dépenser de l'énergie, c'est parce que l'idée de Bitcoin correspondait à leurs valeurs morales et qu'ils avaient « le sentiment d'apporter une contribution bénéfique au monde[^155] » ou bien parce qu'ils entrevoyaient le potentiel profit[^156]. Les personnes prêtes à accepter du bitcoin contre quelque chose d'autre l'ont fait pour les mêmes raisons. NewLibertyStandard, qui été le premier individu à accepter d'échanger des dollars contre des bitcoins en octobre 2009, était notamment convaincu que Bitcoin était « une révolution économique » et « la référence de la monnaie numérique[^157] ».

Comme l'a écrit un internaute anonyme en 2012, « les premiers adeptes de Bitcoin étaient le genre de personnes (du fait de leur intérêt pour les crypto-monnaies) à considérer Bitcoin comme quelque chose de beau[^158] ». Et c'est cette beauté qui a été à l'origine de la réalité monétaire qu'on connaît aujourd'hui.

## La monnaie de la désobéissance {#la-monnaie-de-la-désobéissance .unnumbered}

Quand on présente Bitcoin, la question de sa proposition de valeur se pose immédiatement. Pourquoi Bitcoin ? Qu'est-ce qui le démarque des monnaies étatiques qui sont ses principales concurrentes ? Quel est l'intérêt d'utiliser le bitcoin comme monnaie, et pas le dollar ou l'euro ?

Car le bitcoin est, de par son aspect décentralisé et libre, une moins bonne monnaie que le dollar ou l'euro dans de nombreux cas : il est largement moins accepté, son utilisation est plus difficile, il implique de payer des frais de transaction, son pouvoir d'achat fluctue davantage et il pose plus de risques légaux. Toutes ces raisons font que les monnaies fiat et les solutions centralisées sont (et resteront) plus efficaces que Bitcoin dans la grande majorité des situations.

Cela ne veut pas dire que Bitcoin est inutile, mais seulement qu'il doit être appréhendé d'un point de vue particulier. Bitcoin est un système de monnaie « sans permission », *permissionless*, qui peut être utilisé sans avoir à demander l'autorisation de qui que ce soit. C'est un argent liquide électronique permettant l'échange direct et confidentiel entre particuliers, sans avoir recours à un intermédiaire. Il offre la possibilité d'exercer un contrôle total sur ses unités et de réaliser des transferts sans crainte d'être observé ou censuré, vers n'importe quel destinataire, n'importe où dans le monde et à n'importe quel moment.

Sa proposition de valeur découle de ces simples caractéristiques. En étant pour ainsi dire incontrôlable, Bitcoin constitue un instrument de *désobéissance* aux normes sociales et, surtout, au pouvoir politique. En particulier, il retire aux banques et aux États le pouvoir de contrôle et de sélection des transactions, qui leur permet de superviser l'activité économique, ainsi que celui sur l'émission monétaire, qui leur permet de tirer un revenu de seigneuriage. Bitcoin constitue donc un concept de monnaie résistante à la censure, dans le sens où il est difficile d'empêcher une transaction, et résistante à l'inflation, dans le sens où il est difficile de créer plus d'unités qu'initialement prévues.

Bitcoin se construit en opposition aux autorités en charge, et s'inscrit dans la lutte ancienne contre l'asservissement des hommes. Par son existence, il affirme la primauté du droit naturel sur la loi positive, la supériorité de la propriété individuelle par rapport à la collectivité. Il s'intègre par là dans la tradition libérale du droit de résistance (*jus resistendi*), justifiant la sécession d'un individu ou d'un groupe d'individus face aux lois injustes, droit reconnu par deux grandes révolutions du [xviii]{.smallcaps} siècle, qu'ont été la révolution américaine et la révolution française.

Il est un outil de désobéissance civile, conception ébauchée par Étienne de La Boétie au [xvi]{.smallcaps} siècle, théorisée par Henry David Thoreau en 1849 et mise en pratique par Gandhi dans sa démarche du *satyāgraha* en Inde et par Martin Luther King dans le cadre du mouvement des droits civiques contre la ségrégation raciale aux États-Unis. Il est un message envoyé au souverain terrestre, refusant ses décrets et affirmant : « Je n'utiliserai plus votre monnaie. »

Bitcoin a été créé en vue de gagner en indépendance individuelle. Bitcoin est issu du mouvement cypherpunk, un mouvement de désobéissance technique prônant l'utilisation proactive de la cryptographie sur Internet afin de protéger la confidentialité et la liberté. Lorsque Satoshi Nakamoto a lancé le réseau, il l'a fait sans demander l'autorisation aux autorités en charge, dans le but explicite d'accroître la liberté. Le 6 novembre 2008, en réponse à une personne qui lui disait qu'il ne « \[trouverait\] pas de solution aux problèmes politiques dans la cryptographie », il déclarait ainsi :

« Oui, mais nous pouvons remporter une bataille majeure dans la course aux armements et conquérir un nouveau territoire de liberté pour plusieurs années[^159]. »

De ce fait, il est naturel que le noyau dur de l'activité construite sur Bitcoin se situe à la marge de ce qui est généralement approuvé par le grand public. Bitcoin implique de reprendre sa souveraineté individuelle contre l'autorité, une démarche qui peut être impopulaire quand les lois émanent d'une acceptation majoritaire. Il sert donc à combler une niche de marché plus ou moins grande, dont la taille évolue selon la proportion de la population qui est prête à désobéir.

Parmi les utilisations centrales de Bitcoin, il y a notamment l'opposition politique. En effet, ce dernier peut constituer un moyen alternatif de financement (réception) et de paiement (envoi) pour les organisations politiques, souvent classifiées à l'extrême-droite ou à l'extrême-gauche, dont l'intégrité financière est mise à mal par le pouvoir en place.

L'exemple de Julian Assange et de WikiLeaks est particulièrement illustratif. En effet, suite aux révélations publiées en 2010 sur les pratiques de l'armée étasunienne en Afghanistan et en Irak, l'organisation a subi un blocus financier de la part de Mastercard, Visa, Western Union, Bank of America et d'autres, qui a fait disparaître 95 % de ses revenus[^160]. Cet épisode l'a poussé à accepter les donations en bitcoins en juin 2011 qui, à défaut d'être subtantielles sur le moment, le sont devenues avec la hausse du cours quelques années plus tard.

On peut également citer le cas du lanceur d'alerte Edward Snowden, l'ancien employé de la CIA et de la NSA, qui a révélé en 2013 l'existence d'une surveillance de masse par la NSA d'Internet et du réseau téléphonique aux États-Unis. Celui-ci est depuis poursuivi par les États-Unis pour « espionnage, vol et utilisation illégale de biens gouvernementaux » et s'est exilé en Russie, dont il a acquis la nationalité en 2022. Snowden est un soutien solide de Bitcoin, en ayant fait usage en 2013 pour payer les serveurs qui ont servi à partager les informations de manière anonyme[^161]. Il a également fait la promotion de la cryptomonnaie ZCash pour son modèle de confidentialité, dont il a participé à la cérémonie d'initialisation en 2016.

Un troisième exemple est celui d'Alexeï Navalny, le principal opposant à Vladimir Poutine en Russie, fondateur de la Fondation anti-corruption (FBK) dont les comptes en banques se sont faits geler en 2019 avant qu'elle soit liquidée en 2021. L'activiste a notamment utilisé Bitcoin pour se financer depuis 2017 et l'équivalent de plusieurs millions de dollars ont transité par son adresse[^162]. Selon son bras droit, Leonid Volkov, cet apport en bitcoin aurait représenté 10 % de leur financement total. Navalny a été incarcéré en Russie en janvier 2021 et l'était toujours en novembre 2023.

Une autre utilisation de Bitcoin si situant aussi dans la démarche de désobéissance est le financement de la plateforme de partage d'articles scientifiques Sci-Hub, fondée en 2011 par Alexandra Elbakyan, une jeune femme kazakhe inspirée par les idéaux communistes. Le but du site (toujours en ligne) est de fournir un libre accès au savoir, par la partage gratuit d'articles et d'œuvres en tous genre, au mépris des lois sur le droit d'auteur. En raison de son caractère illégal, la plateforme a accepté les donations en bitcoins dès ses débuts et a reçu des centaines de milliers de dollars par ce moyen[^163]. Elle a également eu des soucis récurrents avec PayPal, sa seule autre source de revenu, qui a clôturé définitivement son compte en 2020.

De manière plus large, Bitcoin est utile dans le contexte géopolitique. Le système n'est pas lié à une juridiction particulière et n'est pas concerné par la notion de frontière. Il permet par conséquent d'envoyer des fonds à l'étranger en échappant aux diverses contraintes et réglementations en vigueur.

C'est pourquoi il peut servir aux personnes émigrées pour envoyer de l'argent à leurs proches restés dans leur pays d'origine. Ces transferts monétaires, appelés *remittances* en anglais, reposent en effet généralement sur des solutions centralisées comme Western Union et MoneyGram, qui facturent souvent des frais élevés pour leurs services.

Dans le même ordre d'idées, Bitcoin peut aussi être utilisé pour contourner les sanctions économiques qu'imposent les différents États à leurs populations respectives dans le contexte de leurs rapports de force. Toute l'utilité de la cryptomonnaie a par exemple pu être constatée suite au début du conflit russo-ukrainien en 2022, lorsque le bloc occidental a décidé d'instaurer des sanctions financières lourdes à l'encontre de la Russie. Bitcoin a ainsi pu servir tant du côté des citoyens russes, qui ne pouvaient plus recevoir de fonds de l'étranger, que des ressortissants ukrainiens habitant dans les régions occupées.

Ainsi, toute personne vivant sous un régime autoritaire et désireuse de contourner ses lois ou de se révolter contre l'ordre établi trouvera un intérêt à Bitcoin. C'est là où se situe le cœur de l'utilisation de Bitcoin : dans ce qui est interdit et dans ce qui peut facilement le devenir.

## La monnaie du marché noir {#la-monnaie-du-marché-noir .unnumbered}

Bitcoin est un système d'argent liquide électronique qui peut être utilisé de manière confidentielle, sans requérir d'autorisation, avec peu de risques de censure. Il est par conséquent particulièrement adapté pour l'activité économique qui échappe à la supervision de l'État et à ses prélèvements, c'est-à-dire ce que nous appelons communément le marché noir.

Le terme « marché noir » est apparu dans la langue française au cours de la Seconde Guerre mondiale sous l'occupation allemande. Il s'agit d'une traduction littérale du mot allemand du même sens, *Schwarzmarkt*, qui daterait de la Première Guerre. Dès l'origine, le terme désignait un marché clandestin où la réglementation du commerce était contournée.

L'expression n'était pas employée auparavant car la réglementation n'était pas assez présente pour donner un nom à ce concept : l'échange de marchandises se faisait sur le marché tout court. Seul existait le terme « au noir » qui servait à qualifier l'activité réalisée de façon non déclarée, cachée au souverain. Mais avec le développement d'une société de plus en plus policée et réglementée reposant sur des lois explicites plutôt que des normes sociales implicites, la nécessité de distinguer le marché réglementé du marché libre s'est fait ressentir, d'où l'émergence de l'appellation.

La notion de marché noir est floue : elle peut recouvrir à la fois l'activité commerciale exercée par des particuliers et celle des trafiquants de grande envergure, la vente de biens et services légitimes comme celle de produits issus de l'exploitation criminelle. C'est pourquoi il est nécessaire de la clarifier. Ici, nous entendons par marché noir l'économie libre où s'échangent, de manière non réglementée et non taxée, des biens et des services, légaux et illégaux, qui ne sont pas des produits directs de l'agression. Cette définition du marché noir inclut le « marché gris » où s'échangent des biens et services légaux par ailleurs (comme le travail au noir) et exclut le « marché rouge » où se monnaie le crime (comme le meurtre, l'extorsion ou l'esclavage).

Pour désigner l'ensemble des activités marchandes qui échappent au contrôle de l'État et à l'impôt, il arrive aussi que les gens parlent d'économie souterraine, d'économie clandestine ou d'économie parallèle. Cette économie rentre dans le cadre plus large de l'économie informelle, qui n'est pas nécessairement marchande et qui comprend des activités comme le travail domestique[^164]. Cette dernière représente une part énorme de l'économie dans les pays en voie de développement.

Le marché noir profite toujours des circonstances restrictives qui pèsent sur l'économie. Durant la Seconde Guerre[^165], son succès provenait des grandes pénuries créées par la guerre, par le contrôle des prix et par les conditions sévères imposées par l'occupant allemand. La population française était en effet soumise à des rationnements drastiques (la ration alimentaire officielle d'un adulte représentait 1100 calories par jour en 1942) et à des prélèvements outranciers, sous forme de pillages, de taxes ou de réquisitions. Le recours au marché noir est alors devenu une question de nécessité. L'économie souterraine a également prospéré au sein des régimes les plus répressifs : c'était notamment le cas du marché noir en Union Soviétique qui représentait une « seconde économie[^166] » sur laquelle reposait la survie du pays.

Mais le marché noir n'est pas qu'un phénomène controversé ; c'est aussi la pierre angulaire d'une véritable doctrine, appelée l'agorisme. L'agorisme (terme dérivé du grec ancien [ágorá]{lang="el"}, *agora* signifiant « place de marché ») est une philosophie politique dérivée du libertarianisme, qui préconise la pratique de l'économie souterraine comme moyen pacifique de réduire l'influence de l'État. Cette doctrine a été théorisée dans les années 1970 par Samuel Edward Konkin [iii]{.smallcaps}[^167], un canadien vivant aux États-Unis, grand lecteur de Mises et Rothbard, qui cherchait à radicaliser la vision développée par l'école autrichienne d'économie. Après avoir pratiqué lui-même sa philosophie, il l'a mise sur papier en 1980 dans un long essai, le *Manifeste néo-libertarien*.

L'idée derrière l'agorisme était de joindre le geste à la parole, en unifiant la théorie libertarienne, fondée sur le principe de non-agression[^168], et la pratique du marché noir (que Konkin appelait la « contre-économie[^169] »), fondée sur la recherche du profit. Il s'agissait d'une stratégie visant à éradiquer l'agression (dont celle de l'État) de manière progressive et à créer une société libre (« l'agora ») par le biais d'actions individuelles intéressées.

L'idée de Konkin était d'appliquer les analyses de Mises et Rothbard à l'économie souterraine. Il suivait une démarche raisonnée qui consistait notamment à prendre en compte le risque lié à l'activité illégale (se manifestant par les amendes, l'emprisonnement et les dommages physiques) comme un risque entrepreneurial. Il écrivait :

« Pourquoi les gens s'engagent-ils dans la contre-économie sans protection ? parce que le gain par rapport au risque qu'ils prennent est plus grand que la perte attendue. Cette affirmation est vraie au sujet de toute activité économique, bien sûr, mais concernant la contre-économie, elle mérite une attention particulière :

Le principe fondamental de la contre-économie est d'échanger du risque contre du profit[^170]. »

Ainsi, l'agorisme consistait bien plus à passer entre les mailles du filet étatique pour améliorer sa vie qu'à jouer les barons de la drogue. Si les activités les plus controversées et moralement sensibles du marché noir sont utiles pour illustrer le mécanisme, elles n'en sont pas moins inenvisageable pour la plupart des gens, qui ont une aversion au risque élevée. Il ne s'agit pas non plus d'un appel à violer la loi sans aucune restriction : le jeu n'en vaut souvent pas la chandelle.

Contrairement aux autres théories politiques qui ne font qu'énoncer des principes, l'agorisme fournissaient à la fois une fin à viser -- l'*agora*, la société sans État -- et un moyen permettant d'y parvenir. La cohérence du processus reposait sur les incitations économiques des individus : les actions clandestines amélioraient directement leur vie à court terme, et contribuaient à réduire la place de l'État à long terme en le privant de son revenu fiscal.

Mais quel rapport avec la monnaie et avec Bitcoin ? La monnaie a toujours été une préoccupation de Samuel Konkin. L'idée agoriste a été développée dans les années 1970 aux États-Unis soit précisément au moment de l'abandon définitif de l'étalon-or et de l'inflation qui s'est ensuivie. Konkin imaginait alors résoudre le problème par l'utilisation d'une banque illégale permettant d'échanger de l'or de manière pratique, mais cette idée comportait des risques trop élevés, comme nous le verrons dans le chapitre [4](#ch:adversaire){reference-type="ref" reference="ch:adversaire"}.

Le marché noir a ainsi manqué d'une monnaie endogène vraiment efficace. Depuis les années 70, l'essentiel de l'économie souterraine a fonctionné grâce aux monnaies fiat disponibles sous forme liquide, et en particulier aux billets verts américains répandus aux quatre coins du monde. L'utilisation des espèces est très pratique, car elles sont acceptées quasi partout, mais elle a pour effet de permettre aux autorités de bénéficier indirectement des activités illégales grâce au prélèvement caché du seigneuriage, issu du privilège de création monétaire. De plus, au vu des récentes évolutions, le contrôle sur la monnaie a tendance à s'accroître et l'argent liquide étatique est voué à devenir de plus en plus anecdotique, ce qui représente une menace existentielle pour le marché noir et la liberté en général.

Les métaux précieux comme l'or et l'argent semblent être des candidats acceptables. Cependant, ils possèdent deux défauts majeurs : leur coût de vérification élevé, ce qui explique le succès de la certification étatique au moyen des pièces frappées ; et leur portabilité réduite, ce qui explique le développement du crédit et l'apparition subséquente des monnaies fiat.

Bitcoin corrige ces insuffisances. Le coût de vérification est celui de l'entretien d'un nœud, qui peut être réparti entre plusieurs personnes, et sa portabilité est supérieure, notamment en ce qui concerne les paiements à distance.

Bitcoin constitue un concept de monnaie numérique particulièrement bien adapté pour le marché noir grâce à sa résistance à la censure et à l'absence de seigneuriage. Bitcoin est une manière pour les agoristes de littéralement « rendre à César ce qui est à César, et à Dieu ce qui est à Dieu » par l'abandon de la monnaie fiat, étroitement liée au prélèvement de richesse de l'État, et par l'utilisation exclusive d'une monnaie libre, neutre et décentralisée par essence.

C'est tout naturellement que les premiers contributeurs à Bitcoin s'inscrivaient dans cette démarche, voire y souscrivaient complètement. Martti Malmi, le jeune développeur finlandais qui a aidé Satoshi Nakamoto au début, avait typiquement ce genre de motivation. En avril 2009, dans une courte introduction présentant Bitcoin sur le forum anarcho-capitaliste de Freedomain Radio, il écrivait :

« Le système est anonyme, et aucun État ne pourrait possiblement taxer ou empêcher les transactions. Il n'y a pas de banque centrale qui puisse déprécier la devise avec la création illimitée de nouvelle monnaie. L'adoption généralisée d'un tel système ressemblerait à quelque chose qui pourrait avoir un effet dévastateur sur la capacité de l'État à se nourrir à partir de son bétail[^171]. »

Cette capacité a été illustrée par l'émergence de la place de marché Silk Road en 2011, qui utilisait le bitcoin comme unique intermédiaire d'échange. Les vendeurs y postaient des annonces, les acheteurs payaient et les produits étaient envoyés par voie postale. La plateforme garantissait la confidentialité des deux parties par l'utilisation du réseau Tor, et protégeait les acheteurs en intégrant un système de réputation pour la sélection des vendeurs et un procédé de dépôt fiduciaire pour arbitrer les échanges. Les produits disponibles sur la plateforme étaient divers mais il s'agissait essentiellement de drogue illicite, et notamment de cannabis. Cet « Amazon de la drogue » générait plus d'un million de dollars de volume mensuel en bitcoins à partir de 2012.

Silk Road a été créée par Ross Ulbricht qui a ouvertement admis avoir été influencé par l'école autrichienne d'économie et par la philosophie agoriste[^172]. Sa place de marché en ligne était dans son esprit un moyen de détruire les structures agressives, et en particulier les cartels de la drogue dont l'influence nuisait aux trafiquants individuels. De manière générale, les initiatives comme Silk Road devaient mettre à bas l'État tel que nous le connaissons. Comme Ross le déclarait dans son entrevue avec Adrien Chen publiée le 1 juin 2011 :

« L'État est la principale source de violence, d'oppression, de vol et de toute forme de coercition. Arrêtez de financer l'État avec l'argent de vos impôts et dirigez votre énergie productive vers le marché noir[^173]. »

Néanmoins, son orgueil et les risques inconsidérés qu'il a pris l'ont mené là où on finit généralement lorsqu'on défie frontalement l'État : en prison. Il a été arrêté en 2013 et condamné à l'emprisonnement à perpétuité sans possibilité de libération conditionnelle en 2015.

Silk Road a été un élément essentiel du développement de Bitcoin, le premier cas d'utilisation majeur de la cryptomonnaie, et son héritage est toujours présent. De nombreux utilisateurs ont ainsi découvert Bitcoin soit en recherchant une mise en application des idées libertariennes (à l'instar de Roger Ver ou de Vitalik Buterin[^174]), soit en cherchant à se procurer de la drogue sur Silk Road (comme Peter McCormack[^175]). Cette particularité est une incarnation de la vision de Konkin, qui voulait réconcilier les « libertariens de bibliothèque » et les « contre-économistes » de l'économie souterraine.

## La proposition de valeur de Bitcoin {#la-proposition-de-valeur-de-bitcoin .unnumbered}

Bitcoin est un concept de monnaie numérique fonctionnant sur Internet, résistante à la censure et résistante à l'inflation. Il diffère de ses alternatives que sont le dollar (et les monnaies fiat en général) et l'or (et les métaux précieux en général), par ses propriétés nouvelles, liées à son absence de tiers de confiance.

Bitcoin est par essence un outil qui donne à l'individu le pouvoir de préserver sa liberté et sa richesse. Grâce à la résistance à la censure, il vise à permettre à quiconque de décider comment il veut dépenser son argent et, par conséquent, de choisir s'il veut le céder à autrui ou non. Grâce à la résistance à l'inflation, il permet à ses utilisateurs de ne pas subir le seigneuriage de l'État, en disposant d'une monnaie dont l'émission est prédéterminée et dont la quantité maximale est limitée.

De ce fait, le cœur de l'utilisation de Bitcoin se situe aux confins de ce qui est autorisé par les puissances de ce monde. Il est principalement, et restera, une monnaie de désobéissance, utilisée dans l'économie parallèle, pour acheter des biens et des services et pour conserver de la valeur à long terme. Avec l'inéluctable numérisation de la monnaie, il pourrait devenir un « territoire de liberté » équivalant à ce qui est aujourd'hui offert par l'argent liquide physique. Il a, après tout, été présenté au monde comme un « argent liquide électronique ».

[^128]: Le concept de cessibilité a été décrit en 1892 par l'économiste autrichien Carl Menger dans son essai *On the Origin of Money*. Le terme en allemand est *Absatzfähigkeit*, qui désigne, pour une marchandise, la capacité à s'écouler facilement, à bien se vendre. Il a été traduit en anglais par *saleability* et *marketability*. Il peut aussi être traduit par vendabilité ou échangeabilité en français.
[^129]: L'économiste Fritz Machlup parlait de « degrés de monétarité » à propos des créances en dollar dans le système bancaire européen (Fritz Machlup, « *Euro-dollar creation: a mystery story* », in *Banca Nazionale del Lavoro Quarterly Review*, vol. 23, no. 94, 1970, p. 225). De même, Hayek écrivait dans *Pour une vraie concurrence des monnaies* en 1976 (p. 93) : « Ceci signifie aussi que, bien que nous supposions habituellement qu'il existe une distinction claire entre ce qui est une monnaie et ce qui n'en est pas -- et la législation s'efforce généralement de poser une telle démarcation --, cette dichotomie n'existe pas dès lors qu'on considère les propriétés qui confèrent à un bien la qualité de monnaie. Ce que nous observons est bien davantage un continuum dans lequel des biens dotés de différents degrés de liquidité, ou dont les valeurs fluctuent indépendamment les unes des autres, se confondent partiellement par le degré auquel ils peuvent être utilisés en tant que monnaie. »
[^130]: L'effet Lindy est le fait que l'espérance de vie future d'une chose non périssable, telle qu'une technique ou une idée, est proportionnelle à son âge actuel.
[^131]: C'est le sens qu'on porte au mot *commodity* en anglais.
[^132]: Le mot salaire vient du latin *salarium*, qui désignait la « ration de sel », puis la « solde pour acheter du sel » versés aux soldats romains dans l'Antiquité : <https://www.lexilogos.com/latin/gaffiot.php?q=salarium>.
[^133]: D'un point de vue légal, la monnaie électronique désigne un type spécifique de monnaie scripturale. L'article L315-1 du *Code monétaire et financier* la définit comme « une valeur monétaire qui est stockée sous une forme électronique, y compris magnétique, représentant une créance sur l'émetteur, qui est émise contre la remise de fonds aux fins d'opérations de paiement définies à l'article L. 133-3 et qui est acceptée par une personne physique ou morale autre que l'émetteur ». C'est pouquoi nous préférons ici employer le terme de monnaie numérique.
[^134]: Carl Menger, *Principles of Economics*, Ludwig von Mises Institute, 2007, pp. 120--121 : <https://cdn.mises.org/principles_of_economics.pdf>.
[^135]: Le chartalisme (du latin *charta*, « papier », « lettre ») est une théorie de la monnaie qui a été développée par l'économiste allemand Georg Friedrich Knapp en 1905 dans son ouvrage *Staatliche Theorie des Geldes*. La théorie monétaire moderne (*Modern Monetary Theory*) forme un néochartalisme.
[^136]: Carl Menger, *Principles of Economics*, Ludwig von Mises Institute, 2007, pp. 261--262.
[^137]: Nick Szabo, *Shelling Out: The Origins of Money*, 2002 ; George Selgin, *The Myth of the Myth of Barter*, 2016 : <https://www.alt-m.org/2016/03/15/myth-myth-barter/>.
[^138]: Bitcoin and Bible Group, *Thank God for Bitcoin: The Creation, Corruption and Redemption of Money*, Whispering Candle, 2020.
[^139]: Ludwig von Mises, *The Theory of Money and Credit*, Yale University Press, 1953, p. 414 : <https://cdn.mises.org/Theory%20of%20Money%20and%20Credit.pdf>.
[^140]: Friedrich Hayek, *Pour une vraie concurrence des monnaies*, Presses Universitaires de France, 2015.
[^141]: « Il n'y a personne pour agir en tant que banque centrale ou réserve fédérale afin d'ajuster l'offre monétaire au fur et à mesure que le nombre d'utilisateurs augmente. \[\...\] En ce sens, il a plus les caractéristiques d'un métal précieux. » -- Satoshi Nakamoto, *Re: Bitcoin open source implementation of P2P currency*, 18 février 2009, <https://p2pfoundation.ning.com/forum/topics/bitcoin-open-source?commentId=2003008:Comment:9562>.
[^142]: Ludwig von Mises, *The Theory of Money and Credit*, Yale University Press, 1953, pp. 120--121.
[^143]: Ludwig von Mises, *The Theory of Money and Credit*, Yale University Press, 1953, p. 110. Voir aussi Ludwig von Mises, *Human Action*, Ludwig von Mises Institute, 1998, p. 405 : <https://cdn.mises.org/Human%20Action_3.pdf>.
[^144]: Ludwig von Mises, *The Theory of Money and Credit*, Yale University Press, 1953, p. 110.
[^145]: Satoshi Nakamoto, *Re: Bitcoin does NOT violate Mises' Regression Theorem*, 27/08/2010 17:32:07 UTC : <https://bitcointalk.org/index.php?topic=583.msg11405#msg11405>.
[^146]: Satoshi Nakamoto, *Re: Bitcoin does NOT violate Mises' Regression Theorem*, 27/08/2010 17:32:07 UTC : <https://bitcointalk.org/index.php?topic=583.msg11405#msg11405>.
[^147]: Hal Finney, *Re: Bitcoin v0.1 released*, 11/01/2009 01:22:01 UTC : <https://www.metzdowd.com/pipermail/cryptography/2009-January/015004.html>.
[^148]: Satoshi Nakamoto, *Re: Current Bitcoin economic model is unsustainable*, 21/02/2010 05:44:24 UTC : <https://bitcointalk.org/index.php?topic=57.msg415#msg415>. -- Il a réitéré cette objection en juillet 2010 : « \[La monnaie\] n'est pas stable par rapport à l'énergie. Ce sujet a fait l'objet d'une discussion. Elle n'est pas liée au coût de l'énergie. L'estimation de NLS basée sur l'énergie était un bon point de départ, mais les forces du marché domineront de plus en plus. » (Satoshi Nakamoto, *Re: Slashdot Submission for 1.0*, 05/07/2010 21:31:14 UTC : <https://bitcointalk.org/index.php?topic=234.msg1976#msg1976>)
[^149]: Konrad S. Graf, *Bitcoins, the regression theorem, and that curious but unthreatening empirical world*, 27 février 2013 : <https://www.konradsgraf.com/blog1/2013/2/27/in-depth-bitcoins-the-regression-theorem-and-that-curious-bu.html>.
[^150]: Ross Ulbricht, *Bitcoin Equals Freedom*, 25 septembre 2019 : <https://rossulbricht.medium.com/bitcoin-equals-freedom-6c33986b4852>.
[^151]: Satoshi Nakamoto, *Re: Bitcoin P2P e-cash paper*, 14/11/2008 18:55:35 UTC : <https://www.metzdowd.com/pipermail/cryptography/2008-November/014853.html>.
[^152]: Hal Finney, *Re: Bitcoin v0.1 released*, 11/01/2009 01:22:01 UTC : <https://www.metzdowd.com/pipermail/cryptography/2009-January/015004.html>.
[^153]: Satoshi Nakamoto, *Bitcoin v0.1 released*, 16/01/2009 16:03:14 UTC : <https://www.metzdowd.com/pipermail/cryptography/2009-January/015014.html>.
[^154]: Satoshi Nakamoto, *Re: Bitcoin open source implementation of P2P currency*, 18 février 2009 : <https://p2pfoundation.ning.com/forum/topics/bitcoin-open-source?commentId=2003008:Comment:9562>
[^155]: Hal Finney, *Re: Bitcoin P2P e-cash paper*, 13/11/2008 15:24:18 UTC, <https://www.metzdowd.com/pipermail/cryptography/2008-November/014848.html>.
[^156]: « J'ai vu le message \[de Hal\] et c'est l'une des raisons pour lesquelles j'ai démarré un nœud si rapidement. Mes systèmes ne font pas grand chose d'autre lorsqu'ils sont inactifs, alors pourquoi ne pas créer des BitCoins ? Et s'ils valent quelque chose un jour\... ? Bonus ! » -- Dustin Trammell, *Re: Bitcoin v0.1 released*, 16/01/2009 01:14:27 UTC.
[^157]: Capture du site web de NewLibertyStandard, décembre 2009 : <https://web.archive.org/web/20091229132559/http://newlibertystandard.wetpaint.com/>.
[^158]: qbg, *Comment: Bitcoin and the Regression Theorem of Money*, 8 décembre 2012 : <https://voluntaryistreader.wordpress.com/2012/12/07/bitcoin-and-the-regression-theorem-of-money/#comment-135>.
[^159]: Satoshi Nakamoto, *Re: Bitcoin P2P e-cash paper*, 06/11/2008 20:15:40 UTC, <https://www.metzdowd.com/pipermail/cryptography/2008-November/014823.html>.
[^160]: WikiLeaks, *Banking Blockade*, 24/10/2011 13:00 UTC, <https://wikileaks.org/Banking-Blockade.html>.
[^161]: Jamie Crawley, « *Edward Snowden says use crypto, don't invest in it: 'Bitcoin is what I used to pay for the servers pseudonymously'* », *Fortune*, 11 juin 2022 :<https://fortune.com/2022/06/11/edward-snowden-says-use-crypto-dont-invest-in-it-bitcoin-is-what-i-used-to-pay-for-the-servers-pseudonymously/>.
[^162]: L'adresse principale d'Alexeï Navalny était .
[^163]: La page de donation se situe à l'adresse <https://sci-hub.se/donate>. L'ancienne adresse (d'après une capture antérieure du site : <https://web.archive.org/web/20160202212649/http://sci-hub.la/>) a reçu 94,42594975 BTC entre le 03/07/2015 et le 14/11/2020. Les autres adresses liées à Sci-Hub sont et .
[^164]: Le travail domestique (cuisine, ménage, linge, éducation des enfants, etc.) était auparavant principalement assuré par les femmes, avant qu'elles n'abandonnent le foyer et que ce travail ne devienne un travail taxé comme un autre. La société promue par l'État moderne est avant tout une société mercantile, où tout se vend et où tout peut être taxé de la naissance à la mort de l'individu.
[^165]: Joël Drogland, « La France du marché noir », *La Cliothèque*, 2 mai 2008 : <https://clio-cr.clionautes.org/la-france-du-marche-noir-1940-1949.html>.
[^166]: Le nom est tiré de l'article « *The Second Economy of the USSR* » écrit par Gregory Grossman en 1977.
[^167]: Le terme « *agorism* » a été forgé par Konkin pour sa présentation au *Free Enterprise Forum* de février 1974.
[^168]: Le libertarianisme se base sur l'axiome de non-agression formulé par l'économiste autrichien Murray Rothbard dans *For a New Liberty: The Libertarian Manifesto* en 1973 : « Aucun individu ni groupe d'individus n'a le droit d'agresser quelqu'un en portant atteinte à sa personne ou à sa propriété \[\...\], "agression" étant défini comme le fait de prendre l'initiative d'utiliser la violence physique (ou de menacer de l'utiliser) à l'encontre d'une autre personne ou de sa propriété. »
[^169]: Le terme contre-économie est calqué sur le mot contre-culture, faisant référence à la culture alternative des années 60, à laquelle Konkin avait participé.
[^170]: Samuel Edward Konkin [iii]{.smallcaps}, *New Libertarian Manifesto*, KoPubCo, 2006.
[^171]: Martti Malmi, *P2P Currency could make the government extinct?*, 9 avril 2009 : <https://web.archive.org/web/20150927195115/https://board.freedomainradio.com/topic/17233-p2p-currency-could-make-the-government-extinct/>.
[^172]: Dread Pirate Roberts, *chat*, 20 mars 2012 : <https://antilop.cc/sr/users/dpr/threads/20120320-1103-chat.html>.
[^173]: Adrian Chen, « *The Underground Website Where You Can Buy Any Drug Imaginable* », *Gawker*, 1 juin 2011 : <https://www.gawker.com/the-underground-website-where-you-can-buy-any-drug-imag-30818160>.
[^174]: « Ce sont les médias en ligne agoristes qui m'ont fait découvrir Bitcoin. L'agorisme ne nécessite peut-être pas d'ordinateurs, mais la technique est l'arme la plus puissante que la liberté ait à sa disposition. » -- Vitalik Buterin, *Re: Bitcoin on AgoristRadio.com*, 21/05/2011 18:36:45 UTC : <https://bitcointalk.org/index.php?topic=9177.msg133853#msg133853>.
[^175]: Nugget's News, *Peter McCormack -- Bitcoin, Addiction & Podcasts* (vidéo), 19 juillet 2019 : <https://www.youtube.com/watch?v=3aDMnE6dnHk>.