# La nécessité de décentralisation {#ch:adversaire}

[]{#enotezch:4 label="enotezch:4"}

[B]{.lettrine}[i]{.smallcaps}tcoin donne aux individus une propriété entière et souveraine sur leur argent. D'une part, il leur permet de l'envoyer à n'importe quelle personne, n'importe où dans le monde, à n'importe quel moment et quel que soit le motif, en empêchant le gel des transactions. D'autre part, il leur permet de préserver pleinement leur pouvoir d'achat en interdisant la création arbitraire d'unités supplémentaires. Par cette double proposition de valeur, Bitcoin s'inscrit dans un rapport antagoniste avec l'État, qui revendique une prérogative exclusive sur la monnaie et un contrôle inquisitorial sur son utilisation.

Souvent présenté comme l'institution qui possède le « monopole de la violence légitime », l'État se caractérise plutôt par le transfert de richesse non consenti qu'il assure. Ce transfert se manifeste de deux manières principales que sont l'impôt, c'est-à-dire le prélèvement direct du contribuable, et le seigneuriage, à savoir la spoliation indirecte de l'épargnant par l'émission de monnaie. Et ces moyens de prélèvement reposent tous deux sur le contrôle monétaire : le premier est facilité par la surveillance et le blocage des transactions ; le second est issu de la maîtrise sur la définition de l'unité de compte.

De ce fait, l'État ne tolère aucune concurrence sérieuse en matière monétaire. En tant qu'outil de liberté, Bitcoin remet ce contrôle en question et constitue en ceci une menace du point de vue étatique. C'est la raison d'être de son architecture distribuée, fondamentale dans sa conception.

Dans ce chapitre, nous étudierons d'abord le transfert de richesse organisé par l'État et ses conséquences. Puis, nous verrons comment le contrôle monétaire a pu se renforcer au cours de l'histoire, et comment il menace de s'accroître à nouveau par l'intermédiaire de la monnaie numérique de banque centrale. Enfin, nous expliquerons en quoi les systèmes alternatifs centralisés ne sont pas viables et pourquoi la décentralisation constitue une nécessité.

## L'État et l'impôt {#létat-et-limpôt .unnumbered}

Du point de vue sociologique, l'État se définit classiquement comme une autorité souveraine qui s'exerce sur un territoire déterminé et sur un peuple qu'elle représente officiellement. Il en ressort trois éléments qui le caractérisent : un pouvoir sur une population, un territoire et une certaine acceptation.

Premièrement, la nature de l'État est d'utiliser la force physique : son existence repose sur la contrainte, imposée par la violence ou la menace de violence, par l'intermédiaire d'une police et d'une armée. Cette violence s'exerce sur un groupe de personnes sous sa domination, appelées des sujets ou des citoyens, dont il restreint la liberté naturelle, le plus souvent au moyen de lois et de décrets délimitant les interdictions. En particulier, il lève un impôt (terme venant du latin *impōnere*, « charger », « faire peser sur ») qui est, dans les faits, un prélèvement de richesse ne disposant pas du consentement individuel[^176].

Deuxièmement, l'autorité de l'État s'exerce au moyen de la domination sur un territoire donné. Cette caractéristique lui permet de consolider son prélèvement au sein de frontières déterminées : puisque les êtres humains ont besoin de la terre (ou de la mer) pour exercer leurs facultés, le contrôle du territoire facilite énormément leur soumission. C'est la domination sur la terre qui explique l'organisation féodale (du latin médiéval *feodum*, « fief ») de l'État dans les sociétés agraires.

L'impôt est aujourd'hui levé grâce à une multitude de contrôles réalisés par l'État. Ces contrôles passent en premier lieu par la surveillance financière, qui s'applique notamment dans le domaine bancaire : les banques et autres institutions financières sont responsables devant l'administration fiscale, à qui elles doivent transmettre les informations douteuses concernant leurs clients. Cette surveillance est facilitée par un certain nombre de lois, comme par exemple les restrictions sur l'utilisation de l'argent liquide. À l'intérieur du territoire, la collecte de l'impôt se base sur le contrôle fiscal, c'est-à-dire l'ensemble des méthodes d'intervention permettant d'examiner les déclarations, de les confronter à la réalité des faits et de réhausser, le cas échéant, les bases d'imposition. La préservation du revenu fiscal de l'État repose également sur l'entrave des flux de richesse sortant du territoire, par le biais des contrôles douaniers et des contrôles de capitaux. Tous ces contrôles sont étroitement liés à la question de la censure financière, traitée dans le chapitre [9](#ch:censure){reference-type="ref" reference="ch:censure"} du présent ouvrage.

La collecte de l'impôt sur le territoire se fait principalement par l'intermédiaire des acteurs économiques établis, même lorsqu'ils ne sont pas directement taxés. En France, la taxe sur la valeur ajoutée, prélevée sur la vente des biens et services, est ainsi payée par le client, mais versée par le commerçant qui doit l'ajouter à son prix de vente. De même, de nombreuses charges fiscales sont retenues à la source par les entreprises mais payées par leurs employés, comme la contribution sociale généralisée et (aujourd'hui) l'impôt sur le revenu. Ce recours à l'impôt « indirect » permet de réduire le nombre de personnes à surveiller et de rendre le prélèvement « indolore » pour ceux qui le paient réellement.

Troisièmement, l'État bénéficie d'une *large acceptation* de la part de la population, qui peut aller de l'approbation active à la résignation passive. C'est cet élément qui le différencie des groupes criminels organisés qui ne bénéficient pas en général d'une telle aura. Bien que temporaire et partielle, cette acceptation est à l'origine de l'idée de « contrat social », qui n'a rien d'un réel contrat juridique, mais qui forme une constatation de la situation existante. L'État tire ainsi son nom du fait qu'il incarne l'état actuel du rapport de force au sein de la société.

L'acceptation de l'État assure la pérennité du prélèvement fiscal, en faisant en sorte que son pouvoir n'ait pas pas besoin d'être maintenu par la force pure. L'État affirme sa légitimité en prétendant représenter les intérêts du peuple qui vit sur son territoire, au moyen d'idéologies diverses, de façon à rendre les contributeurs dociles et à limiter les révoltes.

En particulier, l'État revendique un monopole sur la violence défensive[^177], et garantit le maintien de l'ordre intérieur (par l'intermédiaire de la police) et la défense contre les ennemis extérieurs (par le biais de l'armée). Ce service réel n'est pas réalisé de manière purement altruiste : l'intérêt de l'État est de défendre les forces productives contre les perturbations internes et externes, tout en les empêchant d'organiser elles-mêmes leur propre protection, dans le but de stabiliser son revenu fiscal. Ce monopole s'apparente ainsi à un chantage à la protection accepté par la population comme un moindre mal.

Puisque l'impôt est la pierre angulaire de la construction étatique, son paiement possède un caractère sacré. C'est ce qui explique pourquoi son évitement est systématiquement dénigré, y compris lorsqu'il est légal. C'est aussi la raison derrière la répression sévère de la résistance fiscale, qui passe notamment par la limitation de la liberté d'expression dans le domaine. En France, il est par exemple interdit d'appeler à arrêter de payer l'impôt, sous peine d'une amende de 3 750 € et d'un emprisonnement de six mois[^178].

La capacité de prélèvement de l'État n'est cependant pas infinie. D'abord, il existe une pondération subtile entre le niveau effectif du prélèvement de richesse et la destruction économique induite, qui varie selon la préférence temporelle des bénéficiaires[^179]. Ensuite, le niveau de prélèvement dépend du niveau d'acceptation de la population et il existe nécessairement un point au-delà duquel l'accroissement du taux de prélèvement se traduit par un amoindrissement du prélèvement total, phénomène illustré par la courbe de Laffer. Enfin, la capacité de prélèvement dépend des moyens techniques possédés par l'appareil étatique, notamment en ce qui concerne la surveillance, et des outils à la disposition de la population pour résister fiscalement, ce qui inclut bien entendu Bitcoin.

L'État est donc l'incarnation de la violence institutionnalisée, qui a pour fonction primaire d'assurer un transfert de richesse non consenti individuellement. Plus qu'un groupe de personnes identifié, il doit être bien plus compris comme un ensemble d'actions réalisées par des individus dans un contexte spécifique. Ainsi, nous nous référerons ici à l'État au singulier en tant que concept pouvant se manifester dans des instances particulières plus ou moins indépendantes, mais toujours selon les mêmes principes.

## La monnaie et le seigneuriage {#la-monnaie-et-le-seigneuriage .unnumbered}

Si nous parlons de l'État, c'est parce qu'il entretient une relation étroite avec la monnaie. Comme nous l'avons vu dans le chapitre [3](#ch:monnaie){reference-type="ref" reference="ch:monnaie"}, celui-ci s'est arrogé une prérogative de plus en plus grande sur la définition de l'intermédiaire d'échange, en garantissant d'abord sa certification, puis en contrôlant aujourd'hui son émission. Cet état de fait a conduit certains théoriciens, dont notamment les chartalistes, à adopter une approche fiscale de la monnaie qui fait du paiement de l'impôt la source originelle de la valeur de cette dernière.

Ce lien étroit s'explique par le fait que l'État en tire un bénéfice considérable, le seigneuriage[^180], qui est l'avantage financier direct qui découle de l'émission de monnaie pour l'émetteur. Le seigneuriage constitue en effet la seconde source principale de revenu de l'État, aux côtés de l'impôt, permettant de financer la dépense publique. Il est par nature une spoliation indirecte du détenteur de monnaie, beaucoup plus efficace à court terme que le prélèvement direct du contribuable. L'endettement, souvent cité comme un troisième moyen, n'est en réalité qu'un impôt différé ou un seigneuriage déguisé.

Le seigneuriage est ainsi le fait de tirer profit d'une industrie particulière : la production de monnaie. Il est le résultat de quatre mesures légales fondamentales que sont la contrefaçon légalisée, le monopole sur la production, l'imposition du cours légal et la suspension des paiements[^181]. Comme dans le cas de l'impôt, ces actions sont largement acceptées dans la mesure où elles émanent de la puissance publique.

La contrefaçon légalisée consiste à faire circuler de la monnaie dont le certificat ne correspond pas à ce qui est attendu par la population générale. Typiquement, il s'agit de faire circuler des pièces possédant une teneur moindre en métal que les pièces similaires existantes ou bien de billets représentatifs dont la monnaie de base de garantie est en réalité conservée de manière fractionnaire.

Le monopole sur la production de monnaie est le privilège exclusif d'émission monétaire accordé à une entité, la dédouanant de toute concurrence et lui permettant de vendre sa monnaie à un prix supérieur à ce qu'il aurait été sur le marché libre. Ce privilège est habituellement délégué à une entité contrôlée par l'État comme un hôtel de la Monnaie ou une banque centrale.

Le cours légal est l'obligation imposée aux acteurs économiques d'accepter une monnaie à la valeur nominale dictée par l'État. L'imposition du cours légal peut être restreinte et ne concerner que les paiements différés (c'est le sens de la *legal tender* anglo-saxonne) ou bien être plus large et se rapporter à tous les paiements (comme c'est souvent le cas en Europe continentale[^182]). Il s'agit d'avantager la monnaie dont l'État dispose d'un monopole d'émission en la surestimant par rapport aux monnaies concurrentes.

Ce cours légal a pris plusieurs formes au cours de l'histoire. Il se retrouvait dans le bimétallisme (double étalon) où le ratio entre l'or et l'argent était fixé à une valeur arbitraire, avantageant l'un ou l'autre des deux métaux. Il se manifestait pendant la période de l'étalon-or classique lorsque les certificats représentatifs devaient être échangés au même cours que le numéraire. Il était également institué par l'étalon de change-or qui imposait que les monnaies nationales des pays secondaires aient cours à un taux déterminé par rapport à la livre ou au dollar, le taux du marché étant maintenu artificiellement haut par le contrôle des changes. Aujourd'hui, le cours légal se définit par rapport au cours sur le marché des changes et il se manifeste par l'interdiction de proposer systématiquement un prix différent selon l'intermédiaire d'échange utilisé.

La suspension des paiements consiste, pour une banque centrale, à interrompre momentanément le remboursement de ses clients, auquel cas on parle de cours forcé. Dans le cas des billets représentatifs, la possibilité de recourir à cette mesure légale permettait de ne pas conserver l'intégralité de l'or en réserve, en empêchant les retraits dans le cas d'une chute de confiance.

Depuis l'Antiquité jusqu'au [xix]{.smallcaps} siècle, la monnaie était constituée de pièces de métaux précieux, essentiellement de l'or, de l'argent et parfois du cuivre. Il était donc impossible pour le souverain de créer de nouvelles unités à partir de rien. Cependant, il pouvait dévaluer les pièces existantes en réduisant leur teneur en métal.

À l'époque romaine, le *denarius* d'argent (qui a donné son nom au denier) a été dévalué à de nombreuses reprises, lentement d'abord, avant de voir sa teneur en métal être réduite à l'excès au cours de la crise du [iii]{.smallcaps} siècle. Le seigneuriage retiré a permis à l'Empire romain de continuer à financer sa domination, sans pour autant continuer son expansion territoriale. De même, tous les souverains européens ont procédé à ce type de manipulation au cours du Moyen Âge. Ces pratiques ont notamment été observées par le philosophe chrétien Nicolas Oresme au [xiv]{.smallcaps} siècle.

De plus, cette manipulation des pièces de monnaie a un effet autrement malencontreux : celle de chasser de la circulation la monnaie sous-estimée, qui se retrouve thésaurisée ou exportée à l'étranger. Ce phénomène porte le nom de loi de Gresham, loi économique faisant référence à Sir Thomas Gresham, un grand marchand et financier anglais du [xvi]{.smallcaps} siècle, qui avait établi le lien causal entre la disparition des meilleures pièces d'argent de la circulation et les mesures légales du pouvoir de l'époque[^183]. Cette loi, couramment résumée par l'expression proverbiale « la mauvaise monnaie chasse la bonne », stipule qu'en l'existence d'un taux de change légal fixe entre deux monnaies, la mauvaise monnaie (c'est-à-dire celle qui est surestimée) a tendance à remplacer la bonne monnaie (c'est-à-dire celle qui est sous-estimée) en tant que moyen de paiement dans le commerce. Cette loi s'applique également, dans une moindre mesure, pour la monnaie représentative et pour la monnaie fiat.

Le développement des banques modernes à partir de la Renaissance a provoqué l'apparition des billets de banque convertibles à vue, bien plus pratiques pour déplacer de la valeur dans l'espace. Le pouvoir a repris cette invention à son compte en monopolisant l'émission des billets et en faisant des instruments supposés représentatifs.

Dans ce cas, le seigneuriage consiste à créer plus de billets qu'il n'y a de métal précieux en réserve, c'est-à-dire réaliser une fraude financière. Mais une contrainte subsiste : une grande partie du métal doit être conservée, sous peine de voir les créanciers vider les coffres. L'État peut choisir de suspendre les paiements (ce qu'il a fait dans l'histoire), mais une telle mesure s'accompagne alors d'une baisse drastique de confiance dans les billets par rapport au métal qu'ils sont censés représenter. C'est pourquoi le régime de l'étalon-or est resté relativement stable au niveau monétaire. Il a cependant pavé la voie à un régime autrement plus inflationniste : celui du papier-monnaie.

Le seigneuriage a acquis un rôle majeur avec l'apparition du papier-monnaie, qui est une monnaie fiduciaire basée sur un support physique. Le seigneuriage consiste alors juste à créer plus de billets dont l'usage est imposé sur le territoire, ce qui est considérablement plus efficace que la dévaluation des pièces en métal précieux et la fraude sur les billets représentatifs.

Dès l'origine, le papier-monnaie a permis de financer les projets pharaoniques des États. Il est notamment indissociable de la guerre moderne. L'émission des *greenbacks* américains, désignés comme tels à cause de l'encre verte utilisée pour imprimer le verso, entre 1861 et 1865 a permis de soutenir la guerre de Sécession aux États-Unis. De même, la Première guerre mondiale a été majoritairement financée par la création monétaire et par la réduction de la dette liée à l'inflation.

Pour éviter une fuite trop importante vers des monnaies concurrentes jugées plus fiables, les États ont également mis en place des mesures de contrôle des changes qui réglementaient l'achat et la vente de devises étrangères. Ces mesures servaient à maintenir la valeur de la monnaie à un niveau artificiellement haut, alors même que la confiance dans celle-ci s'effondrait. Le prétexte invoqué était souvent la « lutte contre la spéculation ».

Toutefois, même si l'émergence du papier-monnaie constituait une manne inédite, la capacité de profiter de la monnaie n'est pas devenue illimitée : la production de pièces et de billets fiduciaires et la lutte contre la contrefaçon privée ont un coût incompressible réduisant le seigneuriage. C'est en partie pourquoi il existe aujourd'hui une volonté de remplacer cet argent liquide par une monnaie intégralement numérique.

Enfin, tout comme l'impôt, le seigneuriage repose sur l'acceptation de la population, qui est soutenue en particulier par une limitation de l'expression. En France, il est ainsi interdit de faire douter le public de la solidité de la monnaie, celui qui désobéit à cette loi s'exposant à une amende de 9 000 € et à deux ans de prison[^184].

## L'inflation des prix {#linflation-des-prix .unnumbered}

La principale conséquence du seigneuriage est l'inflation des prix. Ce terme, qui vient du latin *inflatio* signifiant « gonflement », « enflure », « dilatation », désigne la perte du pouvoir d'achat de la monnaie qui se traduit par une augmentation générale et durable des prix. Il s'agit ainsi d'un phénomène qui touche l'économie dans son ensemble à long terme.

Contrairement à ce qui est parfois supposé, toute hausse des prix n'est pas une manifestation de l'inflation. À cause de son caractère durable, l'inflation est par nature structurelle et non conjoncturelle. Les mesures temporaires imposées par un État peuvent faire augmenter les prix, mais cet effet ne constitue pas en soi de l'inflation.

L'inflation des prix est un phénomène qui a pu être observé dans de nombreuses économies. Elle était déjà présente à l'époque de l'Empire romain, dont elle a accompagné l'effondrement à partir du [iii]{.smallcaps} siècle, en culminant sous le règne de l'empereur Dioclétien. Elle a également pu être observée dans nos économies modernes suite aux deux guerres mondiales, dans les années 1970 et plus récemment dans les années 2020.

L'inflation peut provenir d'une augmentation générale de la demande ou d'une diminution de l'offre de biens et de services. Elle peut théoriquement être le fait de plusieurs facteurs comme l'inflation monétaire, la raréfaction de l'énergie, la destruction de richesse par la guerre ou la fuite des capitaux. En pratique, c'est-à-dire dans le cas d'une économie croissante, pacifiée et indépendante, l'inflation des prix à long terme est, en règle générale, une conséquence de l'inflation monétaire.

L'inflation monétaire est l'excédent de production de monnaie par rapport à la production naturelle sur le marché libre[^185]. Elle résulte de la manipulation de la monnaie par le pouvoir en place, qui cherche à en tirer profit par le biais du seigneuriage. Il arrive ainsi régulièrement que l'État sacrifie le pouvoir d'achat de sa monnaie à long terme pour obtenir un revenu à court terme, par exemple dans le contexte d'une crise militaire, politique ou sanitaire.

Le phénomène de l'inflation est souvent mal appréhendé car il n'est pas le phénomène uniforme et instantané que l'on a tendance à se représenter. Une injection de monnaie dans l'économie exerce un effet progressif et différencié sur les prix au fur et à mesure que la monnaie se diffuse par les échanges. C'est ce qu'on nomme l'effet Cantillon, qui a été observé en 1730 par l'économiste physiocrate Richard Cantillon dans son *Essai sur la Nature du Commerce en Général* où il déclarait qu'« une augmentation d'argent effectif \[causait\] dans un État une augmentation proportionnée de consommation, qui \[produisait\] par degrés l'augmentation des prix[^186] ».

Cet effet Cantillon s'applique à l'espace et au temps. La monnaie produite peut se retrouver dans des espaces spécifiques (les aires urbaines par exemple), se concentrer dans certaines régions du monde (hors du territoire national notamment) ou se concentrer dans certains secteurs économiques particuliers (comme la finance). La propagation peut être ralentie par certaines pratiques, comme le paiement de salaires mensuels. Cependant, l'effet de la hausse de la quantité finit par se répercuter progressivement sur l'ensemble de l'économie.

Entretemps, les personnes proches de l'émission monétaire s'enrichissent. Le producteur de monnaie la dépense en apportant une demande supplémentaire, quitte à proposer un prix supérieur pour obtenir le bien désiré. Le commerçant qui la reçoit, devenu momentanément plus riche, réitère cette dépense plus généreuse auprès d'un autre commerçant. Et ce phénomène se poursuit jusqu'à atteindre les confins de la société économique, de telle sorte que les personnes les plus éloignées de l'émission monétaire s'en retrouvent les plus lésées.

L'inflation des prix est donc une manifestation différée de l'inflation monétaire résultant du seigneuriage excessif de l'État. Si le phénomène s'emballe, celui-ci peut conduire *in fine* à la destruction de l'unité de compte, ce qu'on appelle une hyperinflation. Dans ce cas, l'inflation n'est plus nourrie par la production de monnaie (qui peine à suivre le rythme), mais par la fuite de la valeur vers d'autres monnaies jugées plus fortes ou vers des biens liquides.

## Les banques centrales {#les-banques-centrales .unnumbered}

De nos jours, le système monétaire mondial repose sur le modèle de la banque centrale. Une banque centrale est une institution qui possède un monopole d'émission de la monnaie ayant cours légal sur un territoire donné. Tous les États du monde ont recours à une telle institution pour gérer leur monnaie fiat.

La banque centrale est le résultat de la prise de contrôle sur l'activité bancaire par le pouvoir central. La banque moderne, consistant à faire commerce de la monnaie et du crédit, s'est développée au cours de la Renaissance. Elle se basait sur deux innovations majeures : le dépôt à vue et la lettre de change, qui sont devenus le compte courant et le billet de banque, lorsque le crédit s'est popularisé en tant que substitut monétaire.

Le pouvoir a peu à peu centralisé cette activité en créant des banques publiques qui bénéficiaient d'avantages par rapport à leurs concurrentes privées. Ces banques publiques étaient initialement cantonnées à une ville. C'était par exemple le cas de la Banque du Rialto créée à Venise en 1587, de la banque d'Amsterdam fondée en 1609 avec la bénédiction des Provinces-Unies ou bien de la Banque de Stockholm créée en 1656 par Johan Palmstruch. Puis, des banques nationales ont été formées, comme la banque des États du royaume de Suède (plus tard renommée en *Sveriges Riksbank*) qui a été fondée en 1668, la Banque d'Angleterre qui a vu le jour en 1694, ou encore l'éphémère Banque générale, qui s'est développée en France de 1716 à 1720 sous la supervision de l'écossais John Law.

Les banques centrales ont émergé de ces banques publiques en acquérant le monopole d'émission des billets. La Banque d'Angleterre a acquis ce privilège grâce au *Bank Charter Act* de 1844. En Prusse, le décret du 11 avril 1846 a permis à la Banque royale de Prusse de bénéficier d'un monopole d'émission sur le même modèle que le Royaume-Uni. La Banque de France, fondée en 1800 par Napoléon Bonaparte, a vu son privilège d'émission (à l'origine limité à Paris) être étendu à l'ensemble du territoire en 1848. Aux États-Unis, la banque centrale n'a été créée que tardivement avec la fondation de la Réserve Fédérale en 1913.

Contrairement à ce qui est communément affirmé par les responsables politiques, la banque centrale n'est pas indépendante de l'État. Elle repose sur la force de l'État pour assurer son monopole et l'application du cours légal ; et ce dernier dépend de la banque centrale pour prélever un seigneuriage. La banque centrale n'est ainsi qu'une institution qui joue un rôle dans l'appareil étatique.

Cette implémentation des banques centrales a mené à une installation durable de la monnaie fiat papier. D'abord, les billets étaient adossés à une quantité de métal précieux, et notamment à l'or durant la période de l'étalon-or classique de 1873 à 1914. Ensuite, leur convertibilité directe a été interrompue, au début de manière temporaire au cours d'épisodes de cours forcé plus ou moins longs, puis de manière définitive à partir de la Première Guerre mondiale en 1914 pour l'Europe et de la Nouvelle donne de Franklin Roosevelt en 1933 pour les États-Unis. Enfin, toute référence à l'or dans le système monétaire mondial a été abandonnée en 1971, avec l'abrogation de l'étalon de change-or de Bretton Woods par Richard Nixon.

La banque centrale possède aujourd'hui un rôle prépondérant. Elle intervient largement dans l'économie par sa politique monétaire. Ses missions principales sont la limitation de l'inflation des prix, qui se traduit souvent par un objectif de hausse de l'IPC à 2 % par an, et le prêt en dernier ressort[^187], consistant à fournir de la liquidité aux banques en difficulté lors d'un resserrement du crédit. Elle peut avoir d'autres missions secondaires comme le soutien à la baisse du chômage.

Pour réaliser ces missions, trois leviers d'action lui sont généralement octroyés : la production de la monnaie physique, le rachat de titres sur les marchés financiers et l'influence sur l'émission du crédit par le biais de taux directeurs. Tout d'abord, la banque centrale peut avoir pour tâche de fabriquer le papier-monnaie. Mais cette tâche peut également être déléguée. La Fed délègue cette tâche au Bureau de la gravure et de l'impression, la BCE aux banques nationales des États-membres de l'Union Européenne.

Ensuite, la banque centrale peut se rendre sur les marchés financiers afin d'y intervenir. Elle réalise traditionnellement des opérations d'open market, c'est-à-dire des achats et des ventes de titres, en particulier d'obligations publiques (bons du Trésor), sur le marché interbancaire. Les politiques monétaires non conventionnelles lui permettent également de mener des opérations d'assouplissement quantitatif (QE), plus longues et plus agressives, ce qui permet d'apporter de la liquidité pour soutenir l'économie en cas de crise. Mais ces achats permettent surtout de financer la dette de l'État : puisque la taille du bilan est strictement croissante, on peut considérer qu'une partie de ces achats représente un pur seigneuriage.

Enfin, la banque centrale influence l'émission du crédit bancaire, à l'aide de ses taux directeurs. Ces taux, appelés différemment selon les pays, sont généralement au nombre de trois : le taux de refinancement, qui est taux usuel pour lequel les banques commerciales peuvent obtenir de la monnaie centrale, le taux du prêt marginal, qui est le taux de prêt à courte échéance servant à obtenir des fonds en cas d'urgence, et le taux de rémunération des dépôts, le taux d'intérêt payé par la banque centrale pour la conservation de monnaie centrale en réserve. Le premier, le plus important, sert à limiter la création de crédit bancaire ; le deuxième, qui est nécessairement le plus élevé, permet de maintenir le système bancaire en place en cas de crise grave ; le troisième, qui doit être le moins élevé, a pour rôle de décourager ou d'encourager le prêt commercial à court terme. La banque centrale fixe également un niveau de réserves obligatoires. Ces taux ne sont pas des taux d'intérêt issus du marché et peuvent donc être négatifs.

Le fonctionnement des taux directeurs permet à la banque centrale, et donc à l'État, de prélever un seigneuriage en prêtant à intérêt la monnaie centrale aux banques commerciales. Ces dernières peuvent ensuite prêter ces fonds à leurs emprunteurs qui, par leurs actions économiques comme l'investissement et la consommation, les diffuse dans l'économie toute entière.

Dans ce fonctionnement pyramidal, les banques commerciales tirent aussi profit de leur position. Le système bancaire, formé comme un cartel, bénéficie d'un privilège d'émission de crédit et est protégé des conséquences économiques par la banque centrale, qui constitue un prêteur en dernier ressort, et par le Trésor, qui peut procéder à un renflouement externe[^188]. Ce privilège lui permet, dans la mesure où la banque centrale l'autorise, de prélever elles-aussi un seigneuriage sur le crédit qu'elles émettent. De plus, cette situation encourage l'expansion du crédit et stimule les cycles économico-financiers haussiers et baissiers, qui ont des effets terriblement néfastes sur l'économie comme le malinvestissement et les crises récessionnistes.

Ce système banco-monétaire a été largement critiqué au cours des décennies qui ont suivi l'abandon définitif des accords de Bretton Woods en 1971. Satoshi Nakamoto s'est lui-même joint à la critique en février 2009 lorsque, soucieux d'amener les gens à s'intéresser à Bitcoin, il a mis en avant les conséquences de ce fonctionnement bancaire :

« Le problème fondamental de la monnaie conventionnelle est toute la confiance nécessaire pour la faire fonctionner. Il faut faire confiance à la banque centrale pour qu'elle ne déprécie pas la monnaie, mais l'histoire des monnaies fiat est pleine de violations de cette confiance. Il faut faire confiance aux banques pour détenir notre argent et le transférer par voie électronique, mais elles le prêtent par vagues de bulles de crédit avec à peine une fraction en réserve[^189]. »

Les banques centrales sont ainsi issues de la centralisation de l'activité bancaire. Cependant, ce ne sont plus aujourd'hui des banques, dans le sens où elles n'émettent plus des substituts monétaires, mais la monnaie elle-même. Elles sont en effet devenues des institutions de création monétaire, prenant la place des hôtels de la Monnaie qui frappaient les pièces.

Il est intéressant de constater que c'est l'adoption du billet de banque et la prise de contrôle totale sur celui-ci qui ont mené à l'installation durable de la monnaie fiat. En garantissant sa convertibilité, l'État lui a d'abord octroyé un avantage par rapport aux espèces sonnantes et trébuchantes, le billet offrant une portabilité largement supérieure aux pièces de métaux précieux. Une fois le billet devenu monnaie courante, la puissance publique n'a ensuite eu qu'à suspendre progressivement la convertibilité pour conclure la transformation.

De même, une telle prise de contrôle sur les comptes bancaires est aujourd'hui en cours. Avec la monétisation générale du crédit bancaire numérique soutenue par la garantie étatique des dépôts, tous les ingrédients sont présents pour l'accomplissement d'une nouvelle mutation. C'est l'objet du développement de la monnaie numérique de banque centrale.

## La monnaie numérique de banque centrale {#la-monnaie-numérique-de-banque-centrale .unnumbered}

Une monnaie numérique de banque centrale (MNBC), de l'anglais *central bank digital currencies* (CBDC), est une monnaie fiduciaire numérique émise par une banque centrale. Il s'agit d'une sorte de monnaie entièrement numérique qui ne représente pas une créance. Les systèmes informatiques de MNBC sont actuellement en phase de conception tout autour du monde. Leur déploiement pourrait constituer une évolution majeure dans l'histoire de la monnaie *via* l'appropriation indirecte des dépôts bancaires par l'État.

Disposer d'une monnaie qui serait gérée intégralement par une banque centrale et qui concurrencerait la monnaie scripturale des banques commerciales n'est pas une idée nouvelle. Cette idée remonte en effet à une période antérieure à la démocratisation d'Internet. On la retrouve sous la plume de l'économiste keynésien James Tobin, lauréat du prix Nobel, qui faisait une suggestion approchante en 1987 en écrivant :

« Je pense que l'État devrait mettre à la disposition du public un intermédiaire de paiement offrant la commodité des dépôts et la sécurité des espèces, qui serait essentiellement de la monnaie sous forme de dépôt, transférable pour tout montant par chèque ou autre ordre[^190]. »

Avec l'émergence de Bitcoin dans les années 2010, l'idée d'une monnaie numérique gérée par une banque centrale et mise à disposition des particuliers a été remise au goût du jour. Elle est tout d'abord venue de l'intérieur de la communauté de Bitcoin : elle a été évoquée par un utilisateur le 26 mars 2013 sous la forme de « Fedcoin », un concept satirique d'une « une alternative centralisée aux monnaies pair-à-pair » qui serait contrôlée par la Réserve fédérale des États-Unis[^191]. Du côté de l'Europe, l'idée d'un Eurocoin a été évoquée par Bitcoin.fr le 1 avril 2014[^192]. Bien qu'initialement ironique, cette idée a mené à diverses réflexions sur la pertinence d'un tel système et sur les conséquences de sa potentielle implémentation[^193].

Le sujet est devenu plus sérieux au début de l'année 2015 lorsque David Andolfatto, alors vice-président de la Federal Reserve Bank de Saint-Louis, en a fait la promotion dans une présentation donnée durant la *P2P Financial Systems Conference* à Francfort, puis dans un article publié sur son blog[^194]. Sa proposition était de faire en sorte que, contrairement à Bitcoin, le système d'émission monétaire soit contrôlé par la Réserve fédérale, qui se chargerait d'assurer la convertibilité de l'unité numérique en dollars. Son modèle restait néanmoins mesuré : pour Andolfatto, Fedcoin devrait être un système ouvert et anonyme.

Le concept de monnaie numérique de banque centrale a pleinement émergé avec le discours du 2 mars 2016 de Ben Broadbent, gouverneur adjoint pour la politique monétaire à la Banque d'Angleterre, prononcé à la London School of Economics, qui donnait naissance au terme de « central bank digital currency »[^195]. Dans ce discours, le banquier expliquait comment un registre distribué pouvait permettre de remplacer l'actuel modèle de compensation et de règlement interbancaire, d'en élargir l'accès aux acteurs financiers et aux particuliers en leur permettant de posséder un compte auprès de la banque centrale, et de faire ainsi concurrence à l'argent liquide et aux dépôts dans les banques commerciales.

Depuis, le concept a été mis en œuvre de manière expérimentale. La Banque populaire de Chine, qui a monté un programme de recherche (appelé *Digital Currency Electronic Payment* ou DCEP) dès 2014, a commencé à déployer progressivement son yuan numérique (*digital renminbi*) en 2020. La Riksbank suédoise a envisagé de mettre en place une couronne électronique (ou e-Krona) en novembre 2016, qui est toujours en phase de tests.

Aux États-Unis, l'effort est pris en charge par la *Digital Currency Initiative* du MIT Media Lab, une initiative créée en 2015 dans le but « de réunir les esprits les plus brillants \[\...\] pour mener les recherches nécessaires au développement des monnaies numériques et de la technologie blockchain[^196] » et qui a notamment financé certains développeurs de Bitcoin Core comme Gavin Andresen, Wladimir van der Laan et Cory Fields. Cette initiative a abouti au projet Hamilton en février 2022, un prototype de monnaie numérique développé conjointement avec la *Federal Reserve Bank* de Boston[^197].

Du côté de la Grande-Bretagne, la Banque d'Angleterre a annoncé former un groupe de travail en avril 2021 en collaboration avec le trésor de Sa Majesté. En Europe continentale, la BCE a annoncé en juillet 2021 vouloir développer un euro numérique.

Le concept de monnaie numérique de banque centrale se fonde sur un modèle déjà existant : celui de la monnaie numérique interbancaire composée des avoirs monétaires détenus par les banques commerciales auprès de la banque centrale. Cette monnaie est destinée à fluidifier les règlements entre les banques, plutôt que de passer par des espèces. Elle constitue, avec les pièces et les billets en circulation, ce qu'on appelle la monnaie centrale ou monnaie de base. Celle-ci est fiduciaire par nature, dans le sens où elle tire essentiellement sa valeur de la confiance que ses utilisateurs accordent à l'entité qui l'émet et non pas à une propriété physique intrinsèque.

L'idée derrière la monnaie numérique de banque centrale est d'étendre l'accès de cette monnaie interbancaire aux autres entreprises et aux particuliers. Les banques centrales parlent parfois de « MNBC de détail » (*retail CBDC*) pour différencier ce projet de celui d'une modernisation de la monnaie interbancaire existante, qui constituerait une « MNBC de gros[^198] » (*wholesale CBDC*). Nous parlerons ici uniquement de la MNBC de détail.

D'un point de vue technique, une monnaie numérique de banque centrale serait basée sur un registre de compte, distribué entre quelques serveurs grâce à un mécanisme de consensus de type classique, très bien adapté pour traiter un volume transactionnel élevé. La réplication des données financières à différents endroits permettrait d'éviter toute perte liée à une panne ou une cyberattaque.

Le système serait accessible via une identification de l'utilisateur, probablement grâce un système d'identité numérique, dans le but de satisfaire les exigences de lutte contre le blanchiment et le financement du terrorisme. Les transactions des utilisateurs seraient cachées au public, mais pourraient être observées par une autorité homologuée.

Comme tout système informatique, un tel dispositif serait programmable, et des conditions de dépenses pourraient être ajoutées aux fonds. De plus, ce modèle pourrait être modifié au cours du temps pour inclure de nouvelles fonctionnalités.

Les apports directs de la monnaie numérique pour l'utilisateur seraient multiples. D'abord, elle éliminerait le risque de contrepartie lié au crédit : l'utilisateur pourrait jouir théoriquement de tous les avantages apportés par un compte bancaire sans subir le risque de faillite de la banque. Ensuite, elle fournirait une plus grande accessibilité et favoriserait l'inclusion financière en permettant de « bancariser les non-bancarisés » à moindre frais. Enfin, elle automatiserait les opérations financières de façon à améliorer considérablement la qualité des services en ligne.

Grâce à ces avantages, la monnaie numérique de banque centrale paraît représenter un progrès, une modernisation de la monnaie physique dépassée par la numérisation de la société. Toutefois, c'est ignorer son potentiel majeur pour le pouvoir et les inconvénients majeurs pour l'utilisateur individuel.

Pour l'État, le potentiel des monnaies numériques de banque centrale est double. Premièrement, la monnaie numérique de banque centrale a le potentiel d'apporter un contrôle financier total.

D'une part, la généralisation de la monnaie de banque centrale formerait une base légale à partir de laquelle supprimer l'argent liquide. En effet, contrairement au crédit bancaire, la MNBC constituerait une monnaie de base dont il serait aisé de définir le cours légal sur le territoire. On pourrait donc assister à une disparition progressive des supports physiques de la monnaie.

D'autre part, elle permettrait d'améliorer la surveillance financière et offrirait une possibilité d'intervention supérieure, notamment grâce au traitement automatisé par intelligence artificielle. En particulier, une MNBC faciliterait la collecte de l'impôt, en généralisant le prélèvement direct sur le compte du contribuable. Cet aspect est traité dans la section apparentée du chapitre [9](#ch:censure){reference-type="ref" reference="ch:censure"} sur la résistance à la censure.

Deuxièmement, la monnaie numérique de banque centrale possède un potentiel inflationniste non négligeable. D'une part, le remplacement de l'argent liquide permettrait d'éliminer les coûts de production, de distribution et de destruction des supports monétaires (pièces et billets). Cela améliorerait le seigneuriage sur la monnaie de base, en diminuant largement le coût de production. C'est déjà le cas avec la monnaie centrale interbancaire.

D'autre part, le remplacement progressif du crédit bancaire permettrait de récupérer le seigneuriage réalisé sur le crédit par les banques commerciales, comme cela se fait déjà partiellement grâce au taux de refinancement. Cette capture se ferait aux dépend des banques, qui verrait leur capacité à prêter être réduite voire annihilée. C'est pourquoi elles devraient gagner quelque chose au change, par exemple en obtenant à la place un rôle d'intermédiaire dans le système.

Les banques commerciales pourraient être pleinement absorbées par la banque centrale, dont elles deviendraient les succursales. Ainsi, le vieux rêve marxiste de centraliser le crédit entre les mains d'une seule banque serait réalisé[^199]. À l'instar de la Gosbank, la banque centrale de l'Union soviétique et seule banque autorisée 1932 et 1987, cette banque unique suivrait les directives du pouvoir central en accordant des prêts financés par création monétaire, non aux emprunteurs solvables, mais aux entités favorisées par la planification économique.

Tout ceci constitue une prospective qui semble peu probable au premier abord. Quand on voit les dangers que créent la généralisation d'un tel système, on peut penser que la population ne pourrait pas accepter cette mutation. Ces systèmes ne sont en effet pas naturellement adoptés par les citoyens, comme en témoignait l'échec de l'eNaira au Nigéria en 2023. En Occident, une réaction de rejet existe, notamment à droite, et des personnalités publiques attachées aux libertés ont déjà affirmé leur opposition, comme le lanceur d'alerte Edward Snowden qui a qualifié cette potentielle monnaie numérique de « monnaie cryptofasciste[^200] » en octobre 2021.

L'acceptation promet donc d'être complexe, mais elle est loin d'être impossible. Elle pourrait reposer sur des incitations légales encourageant l'utilisation de la MNBC et pénalisant son refus, par la récompense et la punition. La récompense serait constituée de diverses subventions pour encourager l'usage, versées aux commerçants et aux consommateurs, comme cela est déjà fait en Chine dans le cadre du yuan numérique. La punition, qui arriverait dans un second temps, pourrait se composer de l'imposition d'un cours légal qui contraindrait les commerçants à accepter la monnaie numérique centrale, du refus d'accès aux services publics aux personnes ne disposant pas d'un compte à la banque centrale, et de la censure des opinions anti-MNBC, jugées complotistes.

Quoi qu'il en soit, la monnaie numérique de banque centrale repose, comme pour toute mesure étatique, sur l'acceptation de la population générale. L'opinion publique est donc le champ de bataille ici, mais on est en droit d'imaginer que l'État l'emportera au bout d'une période plus ou moins longue, comme il l'a fait avec le papier-monnaie. Dans ce cas, Bitcoin deviendrait la seule porte de sortie monétaire viable pour la résistance.

## L'arbitrage juridictionnel {#larbitrage-juridictionnel .unnumbered}

Un concept régulièrement invoqué comme un moyen de protéger se liberté individuelle face au contrôle de l'État est celui d'« arbitrage juridictionnel », terme calqué sur l'anglais *jurisdictional arbitrage*. Il s'agit, pour une personne, de tirer parti des divergences qui existent entre des juridictions concurrentes pour optimiser ses conditions de vie. La forme la plus simple de cet arbitrage est l'expatriation fiscale qui consiste à émigrer pour bénéficier d'un taux de prélèvement moins élevé. Cette méthode aurait aussi pour conséquence d'inciter les États, par l'effet de la concurrence, à respecter la liberté de leurs citoyens, et serait de ce fait une forme de « vote avec ses pieds ».

L'arbitrage juridictionnel est un phénomène qui a émergé avec la baisse drastique du coût de changement de juridiction ayant eu lieu au cours des siècles passés, par l'assouplissement des restrictions migratoires, la baisse des frais de voyage et l'accroissement de la liquidité des actifs. De plus, la facilitation de la communication liée à l'arrivée d'Internet a amplifié cet effet en fournissant aux individus un moyen de se soustraire partiellement à l'influence de leurs autorités locales. C'est pourquoi cette stratégie est aujourd'hui beaucoup mise en avant.

La notion d'arbitrage juridictionnel a été notamment décrite par les auteurs à succès Rees-Mogg et Davidson dans leur ouvrage *The Sovereign Individual* publié en 1997, dont la thèse principale était de prédire le recul des États-Nations face à l'innovation technique. Ils y formulaient un théorème d'inéquivalence qui, en opposition à l'équivalence ricardienne, postulait que les acteurs économiques ne réduiraient pas leur consommation par anticipation d'une hausse d'impôt due à une relance budgétaire, mais changeraient de juridiction :

« À l'Ère de l'Information, \[\...\] la personne rationnelle ne réagira pas à la perspective d'une augmentation des impôts pour financer les déficits en augmentant son taux d'épargne ; elle déplacera son domicile ou effectuera ses transactions ailleurs. \[\...\] Il faut donc s'attendre à ce que les Individus Souverains et les autres personnes rationnelles fuient les juridictions ayant d'importants engagements non financés[^201]. »

Cette vision était également partagée par les cypherpunks, dont beaucoup voyaient le cyberespace émergent comme une juridiction indépendante à part entière, hors d'atteinte de l'État[^202]. Ils envisageaient en particulier l'émission d'une cybermonnaie échappant au contrôle des États. C'était le cas d'Eric Hughes, qui confiait au journaliste Kevin Kelly en 1994 :

« La question la plus importante est la suivante : quelle est l'ampleur des flux monétaires sur les réseaux avant que l'État n'exige la déclaration de chaque petite transaction ? Car si les flux peuvent devenir suffisamment importants, au-delà d'un certain seuil, il pourrait y avoir suffisamment de fonds agrégés pour inciter économiquement un service transnational à émettre une monnaie, et les actions d'un État n'auraient pas d'importance[^203]. »

Une des conséquences de l'arbitrage juridictionnel généralisé est l'émergence naturelle d'une monnaie saine. Puisque, dans l'acception naïve du concept, les États sont en concurrence et que les individus peuvent se déplacer librement, ces derniers finiront par favoriser la monnaie la moins taxée, c'est-à-dire celle empêchant le plus le prélèvement involontaire. On pourrait ainsi voir des États émettre une monnaie basée sur l'or, ou sur le bitcoin, pour faire concurrence aux autres devises et bénéficier d'un attrait supplémentaire pour prospérer[^204].

Cependant, cette théorie séduisante résiste difficilement à l'épreuve de la réalité, car elle néglige les rapports de domination qui existent entre les États dans le cadre de leur interaction géopolitique. Les États ne sont en effet pas des entités indépendantes : ils sont sans cesse en lutte pour prélever un revenu sur des populations, principalement par leur contrôle du territoire, un conflit qui peut se manifester, au niveau le plus extrême, par la guerre. Ces rapports de domination s'exercent aujourd'hui au niveau mondial, car la baisse du coût du transport et des télécommunications a non seulement amplifié l'arbitrage juridictionnel, mais a aussi étendu l'interaction des États entre eux.

Cette théorie fait en particulier abstraction d'un phénomène appelé l'impérialisme, qui est la volonté d'un État d'étendre son pouvoir au-delà de ses frontières naturelles, et qui se manifeste actuellement par les actions des États-Unis, de la Russie et de la Chine dans leurs sphères d'influence respectives. En effet, un État qui s'affaiblit en renonçant à une partie de son revenu fiscal (même si la relation n'est pas exactement proportionnelle) devient plus sensible à une ingérence étrangère impérialiste. C'est pour cette raison que la concurrence entre les États est beaucoup moins économique que ce qu'on imagine, celle-ci étant soumise à des interventions politiques comme l'application de sanctions qui restreignent les flux commerciaux, financiers et migratoires vers et depuis l'État concerné.

L'une des facettes de l'impéralisme est l'impérialisme monétaire, qui consiste à favoriser, par la violence ou la menace de violence, l'usage d'une monnaie sur un territoire étranger pour en retirer un avantage[^205]. L'avantage visé ordinairement est le revenu de seigneuriage supplémentaire rendu possible grâce à une plus grande utilisation de la monnaie, quelque chose qui est parfois schématisé par l'idée que l'État dominant « exporte son inflation ». C'est précisément ce qu'ont pratiqué les États-Unis avec le dollar depuis le début du [xx]{.smallcaps} siècle, notamment au moyen du système d'étalon de change-or de Bretton Woods.

Il est ainsi illusoire de croire qu'un État dominant puisse tolérer qu'un État sous son influence émette, ou autorise ses citoyens à émettre, une meilleure monnaie utilisable à grande échelle. L'arbitrage juridictionnel ne s'applique ici qu'à la marge, c'est-à-dire dans la mesure où il n'affaiblit pas le pouvoir central de manière significative. La réelle façon de changer les choses dans le domaine monétaire à moyen terme repose sur la désobéissance individuelle.

## Les monnaies alternatives centralisées {#les-monnaies-alternatives-centralisées .unnumbered}

Face à cet ordre monétaire imposé par la force de façon plus ou moins directe, certaines personnes ont tenté de construire des systèmes alternatifs. Nous ne parlons pas de monnaies locales complémentaires sans ambition ; nous parlons de monnaies dont le but était de représenter un véritable contrepoids à la monnaie étatique. Et les exemples les plus représentatifs de ces réelles alternatives nous viennent des États-Unis.

Les États-Unis possèdent en effet une grande culture des monnaies privées, conformément à l'esprit de liberté individuelle qui les a caractérisés. Pendant la période coloniale et durant la première moitié du [xix]{.smallcaps} siècle, la frappe privée de pièces était tout à fait autorisée et pratiquée. De même, l'activité bancaire a été relativement libre à partir de 1837, année de fin du mandat de la *Second Bank of the United States*, la banque nationale de l'époque.

Cette liberté monétaire et bancaire a été cependant interrompue par les mesures prises à la suite de la guerre de Sécession. D'une part, une loi du Congrès du 8 juin 1864 a interdit la frappe privée des pièces[^206]. D'autre part, les *National Banking Acts* de 1863 et 1864 ont définitivement mis fin à l'horizontalité et l'indépendance des banques.

C'est à cette occasion qu'a été fondé le *Secret Service*, une agence étatique ayant pour mission de lutter contre le faux-monnayage et la fraude financière en général. Créé le 14 avril 1865, le jour de l'assassinat d'Abraham Lincoln, il servait, d'une façon détournée, à affermir le monopole sur la production de monnaie.

Cette transition a été finalisée avec la création de la Réserve Fédérale en 1913 et la prohibition de la détention d'or promulguée par l'ordre exécutif 6102 signé par F.D. Roosevelt le 5 avril 1933.

Après l'abandon de toute référence à l'or dans le système monétaire mondial (et l'abrogation consécutive de l'ordre exécutif en 1975) et le développement d'Internet, l'idée de déployer une monnaie privée est réapparue. Puisque l'État fédéral pouvait gérer arbitrairement sa monnaie, pourquoi ne pouvait-il pas en être autant des individus ? C'est ainsi que des individus ont entrepris, dans une démarche purement hayekienne, de déployer leur propre monnaie sur le marché. Parmi ces projets de monnaie privée, nous pouvons en citer quatre : ALH&Co, le Liberty Dollar, e-gold et Liberty Reserve.

Le premier était ALH&Co, une banque libre offrant la possibilité à ses clients d'avoir des comptes bancaires libellés en or ou en dollars[^207]. Cette banque a été créée par Anthony L. Hargis, un libertarien proche de Samuel Edward Konkin et de son idée agoriste. Bien que la banque elle-même faisait toutes les démarches pour rester légale, elle n'empêchait pas l'évasion fiscale. Konkin lui-même a décrit le fonctionnement de ALH&Co dans son ouvrage *Counter-Economics* publié à titre posthume[^208].

Les clients pouvaient rédiger des « ordres de transfert » qui fonctionnaient comme des chèques bancaires entre les différentes entreprises qui les reconnaissaient, ou bien les soumettre à AHL&Co et recevoir en retour un chèque bancaire classique ou demander à ALH&Co de payer leurs factures régulières. ALH&Co a existé pendant près de 30 ans, entre 1976 et 2004, du fait de son caractère confidentiel. À un moment donné, la banque avait 253 clients et utilisait 9 comptes bancaires classiques sur lesquels étaient déposés 7,2 millions de dollars.

En mai 1993, les locaux d'ALH&Co ont subi une descente des agents fédéraux, suite à un signalement de suspicion de blanchiment d'argent lié au trafic de drogue. Les agents se sont emparés des dossiers des clients. Cependant, les opérations d'ALH&Co on pu continuer pendant une décennie.

Hargis a finalement été inculpé en mars 2004, et ALH&Co a définitivement été fermée. L'IRS a estimé que l'évasion fiscale des clients s'élevait à 24 millions de dollars.

Le deuxième exemple contemporain de monnaie privée aux États-Unis est le Liberty Dollar, une monnaie basée sur l'or et l'argent qu'on pouvait retrouver sous forme de pièces d'argent, de billets représentatifs et, un peu plus tard, d'unités électroniques. Le Liberty Dollar a été créé en 1998 par Bernard von NotHaus *via* son organisation à but non lucratif NORFED.

Ce système a connu un certain succès, notamment après l'introduction du système de monnaie numérique en 2003. Outre les pièces de monnaies en circulation, les coffres de NORFED contenaient environ 8 millions de dollars en métaux précieux pour assurer la convertibilité de la devise, dont 6 pour garantir l'unité numérique[^209].

Toutefois, en septembre 2006, la Monnaie des États-Unis, l'institution en charge de frapper et mettre en circulation les pièces de monnaie américaines, a émis un communiqué de presse, écrit conjointement avec le département de la Justice, dans lequel elle concluait que les « médaillons » de NORFED violaient la section 486 du titre 18 du Code des États-Unis et constituaient « un crime[^210] ». Le communiqué rappelait également que les pièces frappées ressemblaient au dollar ce qui s'apparentait à de la contrefaçon.

Après une descente du FBI dans les locaux de NORFED en 2007, les violations ont été retenues contre NotHaus et ses associés, qui ont été arrêtés en 2009 et jugés en mars 2011. En conséquence de ce jugement, les pièces pouvaient être considérées comme de la contrebande et être saisies comme telles. Les ventes de ces pièces ont également été interdites sur eBay en décembre 2012, sous la pression du Secret Service. En 2014, Bernard von NotHaus a été condamné à six mois d'assignation à résidence et à trois ans de liberté conditionnelle.

Le Liberty Dollar n'était pas inconnu des premiers utilisateurs de Bitcoin. Ainsi, Dustin Trammell, l'un des premiers opérateurs de nœud sur le réseau, s'intéressait à ce système avant de découvrir la monnaie de Nakamoto comme en témoigne son article sur le sujet en décembre 2008[^211].

Le troisième cas de monnaie privée est l'e-gold, une « devise en or numérique » (*digital gold currency*) transférée électroniquement et garantie à 100 % par une quantité équivalente en or conservée en lieu sûr. Le système e-gold a été co-fondé par Douglas Jackson et Barry Downey en 1996, deux ans avant PayPal. Douglas Jackson était un oncologue américain vivant en Floride. Adepte de Hayek, il souhaitait créer une meilleure monnaie avec e-gold.

L'e-gold était par essence une monnaie représentative, chaque montant d'e-gold pouvant être converti en or réel. La détention et la conversion d'or était administrée par une société créée pour l'occasion et basée aux États-Unis, *Gold & Silver Reserve Inc.* (G&SR). La société garantissait également de l'e-silver, de l'e-platinum et de l'e-palladium sur le même modèle.

Le système informatique était géré par une deuxième entreprise, *e-gold Ltd.*, enregistrée à Saint-Christophe-et-Niévès dans les Caraïbes. Pour l'époque, il était très performant, mettant à profit un système à règlement brut en temps réel inspiré du virement interbancaire. Le système tirait profit des navigateurs web et en particulier de Netscape, de sorte que chaque client pouvait avoir accès à son compte depuis le site web.

Le système e-gold a rencontré ainsi un grand succès, à tel point qu'il représentait à un moment donné le deuxième système de paiement en ligne mondial derrière PayPal. À son apogée en 2006, il garantissait 3,6 tonnes d'or, soit plus de 80 millions de dollars, traitait 75 000 transactions par jour, pour un volume annualisé de 3 milliards de dollars, et gérait plus de 2,7 millions de comptes.

Toutefois, ce succès fulgurant a été de courte durée. Au terme d'une enquête menée par le Secret Service, Douglas Jackson, ses deux sociétés et ses associés ont été inculpés le 27 avril 2007 par le département de la Justice pour facilitation de blanchiment d'argent et activité de transfert d'argent sans licence.

Jackson a été condamné à 3 ans de liberté surveillée, incluant 6 mois d'assignation à résidence sous surveillance électronique, et à 300 heures de travail communautaire. Ses deux entreprises ont dû payer une amende de 300 000 \$. Après une tentative infructueuse d'obtenir une licence, e-gold a dû fermer ses portes définitivement en novembre 2009.

Un indicateur du succès d'e-gold est l'émergence de systèmes similaires de devise en or numérique : nous pouvons citer GoldMoney, fondé par James Turk et son fils en février 2001, qui s'est aujourd'hui adapté aux réglementations financières ; e-Bullion, fondé par James Fayed en juillet 2001 et fermé en 2008 ; et Pecunix fondé par Simon Davis en 2002, entreprise enregistrée au Panama, qui a fermé ses portes en 2015, dans le cadre d'une escroquerie de sortie. Le Liberty Dollar électronique (eLD) lancé en 2003 ne faisait ainsi que suivre la vague.

Ces devises en or numérique étaient encore utilisées du temps de Bitcoin, de sorte que ses premiers utilisateurs en avaient connaissance. Satoshi Nakamoto lui-même savait bien comment ces systèmes fonctionnaient, comme le montre l'un de ses courriels adressé à la *Cryptography Mailing List*[^212]. De même, Ross Ulbricht avait envisagé d'utiliser Pecunix pour Silk Road avant de trouver Bitcoin[^213].

Le quatrième et dernier exemple de projet de monnaie privée était le système Liberty Reserve, qui permettait de détenir et de transférer des devises indexées sur le dollar étasunien, sur l'euro ou sur l'or. Le système était la création d'Arthur Budovsky, un Américain d'origine ukrainienne, aux côtés de Vladmir Kats. En 2006, Budovsky s'est expatrié au Costa Rica, qui était alors considéré comme un paradis fiscal facilitant le blanchiment d'argent, où il a enregistré sa société, Liberty Reserve S.A.

L'inculpation d'e-gold en avril 2007 a profité grandement à Liberty Reserve qui a pu prendre la relève. Le système a ainsi rencontré un grand succès. En mai 2013, l'acte d'accusation du département de la Justice étasunienne estimait que Liberty Reserve possédait plus d'un million d'utilisateurs dans le monde, dont plus de 200 000 aux États-Unis, et traitait 12 millions de transactions financières annuellement, pour un volume combiné de plus de 1,4 milliards de dollars.

Toutefois, ce succès s'est accompagné de complications sérieuses. En 2009, la *Superintendencia General de Entidades Financieras* (SUGEF) costaricaine s'est intéressée au cas de Liberty Reserve, lui demandant d'obtenir une licence (chose qu'elle n'est pas parvenue à faire). En mars 2011, une enquête a été ouverte. En novembre 2011, c'est au tour du FinCEN étasunien qui délivre un avis selon lequel LR était « utilisée par les criminels pour effectuer des transactions anonymes[^214] ».

La fin de Liberty Reserve a été retentissante, au terme d'une opération coordonnée de manière internationale. Le 24 mai 2013, Arthur Budovsky et les principaux gestionnaires de Liberty Reserve ont été inculpés et arrêtés, dans des juridictions différentes : en Espagne, aux États-Unis et au Costa Rica. Après environ un an et demi de détention, en octobre 2014, Arthur Budovsky a été extradé de l'Espagne vers New York aux États-Unis, où s'est déroulé son procès. En 2016, Arthur Budovsky a finalement plaidé coupable pour blanchiment d'argent, et, a été condamné à 20 ans de prison ferme.

Liberty Reserve a probablement été la dernière monnaie libre centralisée de grande envergure sur Internet. Le système était encore massivement utilisé lorsque Bitcoin faisait ses premiers pas. Liberty Reserve a ainsi été utilisé pour acheter du bitcoin sur les toutes premières plateformes de change, y compris sur la fameuse plateforme Mt. Gox !

Si l'on tente de récapituler, il est *de facto* interdit de fournir des services bancaires sans licence (ALH&Co), de frapper ses propres pièces de monnaie et d'imprimer ses propres billets (Liberty Dollar), ou de gérer des comptes électroniques en or (e-gold) ou dans la devise nationale (Liberty Reserve), dans la mesure où cela fait concurrence à l'État. Bien qu'il y ait des raisons multiples aux fermetures de ces systèmes, on ne peut que constater que toutes les alternatives sérieuses au système monétaire étatique ont été éliminées[^215].

Le monopole monétaire est souvent imposé subtilement excluant les concurrents potentiels du marché par des lois liées à la contrefaçon ou au blanchiment d'argent. C'est pour cette raison qu'il n'y a aujourd'hui aucune alternative légale. C'est pourquoi les innovations dans le domaine financier, comme PayPal ou GoldMoney, se sont conformées aux réglementations existantes : pour survivre[^216].

L'intervention étatique est là pour s'immiscer dans le système monétaire et le contrôler, en détruisant au besoin les alternatives. C'est pour résister à cette force inouïe que Bitcoin a été conçu tel qu'il existe aujourd'hui.

## Bitcoin contre l'État {#bitcoin-contre-létat .unnumbered}

L'État est ainsi l'incarnation organisée, territorialisée et institutionnalisée du transfert de richesse non consenti. En tant que tel, le contrôle sur la monnaie constitue logiquement un élément qu'il revendique comme sa prérogative, d'autant plus qu'il en tire un revenu, appelé le seigneuriage. Au fil du temps, ce contrôle sur la monnaie est devenu de plus en plus pernicieux, et il s'est accéléré avec l'émergence de la banque durant la Renaissance. L'usage des billets de banque a progressivement été récupéré par l'État au moyen d'une banque centrale, qui s'est arrogé le monopole exclusif sur leur production, jusqu'à les transformer en papier-monnaie. De même, l'usage des dépôts bancaires, qui est aujourd'hui surveillé et contrôlé minutieusement, pourrait être repris dans un futur proche par l'État par le biais de la monnaie numérique de banque centrale.

À moyen terme, il est illusoire de croire que l'État renoncera à son prélèvement, ou même le rendra plus transparent : il faudrait pour cela que ses bénéficiaires demandent eux-mêmes cette transition. On pourrait croire qu'un petit État aurait la possibilité et l'intérêt géostratégique de le faire, mais ce serait ignorer les vélléités impérialistes des puissances dominantes. Il ne suffit donc pas de faire tourner un serveur dans une juridiction accomodante pour gérer une monnaie numérique comme l'a montré le cas de Liberty Reserve.

C'est pourquoi Bitcoin est comme il est. Il est spécifiquement conçu pour résister à l'intervention de l'État et constitue une tentative de construire une alternative robuste au système monétaire actuel. Bitcoin résout cette problématique en distribuant le fonctionnement du système au sein d'un réseau pair-à-pair de nœuds. Cette distribution à égalité permet de partager les risques entre les personnes qui s'en occupent, et de faire en sorte que la sécurité du système repose sur leurs actions économiques combinées plutôt que sur celle d'un seul individu ou d'une seule entreprise.

[^176]: Même si l'on considère que l'impôt constitue un « mal nécessaire », ou qu'il se justifie par l'« intérêt général » ou par la « démocratie », il n'en demeure pas moins, par nature, un transfert de richesse non consenti, c'est-à-dire un vol pour le dire crûment.
[^177]: Comme l'écrivait Max Weber en 1919 : « L'État est l'institution qui possède, dans une collectivité donnée, le monopole de la violence légitime. » -- Max Weber, *Le savant et le politique*, 10/18, 2002.
[^178]: L'article 1747 du *Code général des impôts* dispose : « Quiconque, par voies de fait, menaces ou manoeuvres concertées, aura organisé ou tenté d'organiser le refus collectif de l'impôt, sera puni des peines prévues à l'article 1er de la loi du 18 août 1936 réprimant les atteintes au crédit de la nation \[c'est-à-dire de deux ans de prison et d'une amende de 9 000 euros\].
[^179]: Voir Hans-Hermann Hoppe, « La préférence temporelle, l'État et le processus de décivilisation », in *Démocratie, le dieu qui a échoué*, 2020, Éditions Résurgence.
[^180]: Le nom « seigneuriage » est issu de l'ancien français *seignorage*, qui désignait le privilège de battre monnaie au Moyen Âge, généralement réservé aux seigneurs féodaux.
[^181]: Jörg Guido Hülsmann, *The Ethics of Money Production*, Ludwig von Mises Institute, 2008.
[^182]: Par exemple, le cours légal de l'argent liquide est imposé en France par l'article R642-3 du code pénal : « Le fait de refuser de recevoir des pièces de monnaie ou des billets de banque ayant cours légal en France selon la valeur pour laquelle ils ont cours est puni de l'amende prévue pour les contraventions de la 2e classe. »
[^183]: La loi de Gresham a été formalisée par l'économiste écossais Henry Dunning Macleod dans ses *Elements of Political Economy* publiés en 1858.
[^184]: L'article 1 de la loi du 18 août 1836 réprimant les atteintes au crédit de la nation dispose : « Sera puni de deux ans de prison et d'une amende de 9 000 euros quiconque, par des voies ou des moyens quelconques, aura sciemment répandu dans le public des faits faux ou des allégations mensongères de nature à ébranler directement ou indirectement sa confiance dans la solidité de la monnaie, la valeur des fonds d'État de toute nature, des fonds des départements et des communes, des établissements publics et, d'une manière générale, de tous les organismes où les collectivités précédentes ont une participation directe ou indirecte. »
[^185]: Cette définition nous vient de Guido Hülsmann pour qui l'inflation est « l'augmentation de la quantité nominale d'un moyen d'échange au-delà de la quantité qui aurait été produite sur le marché libre ». -- Jörg Guido Hülsmann, *The Ethics of Money Production*, p. 85.
[^186]: Richard Cantillon, *Essai sur la Nature du Commerce en Général*, McMaster University Archive for the History of Economic Thought, 1755.
[^187]: Le rôle de prêteur en dernier ressort de la banque centrale a été théorisé au cours du [xix]{.smallcaps} siècle. -- Henry Thornton, *An Enquiry into the Nature and Effects of the Paper Credit of Great Britain*, 1802 ; Walter Bagehot, *Lombard Street: A Description of the Money Market*, 1873.
[^188]: Les clients des banques commerciales sont encouragés à garder leurs fonds en banque en étant partiellement couverts contre le risque de faillite par un système de garantie des dépôts, géré par exemple par le Fonds de Garantie des Dépôts et de Résolution (FGDR) en France et par la *Federal Deposit Insurance Corporation* (FDIC) aux États-Unis.
[^189]: Satoshi Nakamoto, *Bitcoin open source implementation of P2P currency*, 11 février 2009 : <https://p2pfoundation.ning.com/forum/topics/bitcoin-open-source>.
[^190]: James Tobin, « *The Case for Preserving Regulatory Distinctions* », in *Proceedings - Economic Policy Symposium - Jackson Hole*, 1987, pp. 167--205 : <https://www.kansascityfed.org/documents/3828/1987-S87TOBIN.pdf>.
[^191]: peculium, *Fedcoin: A centrally-issued alternative to peer-to-peer currencies*, 26 mars 2013, archive : <https://web.archive.org/web/20130404231341/http://peculium.net/2013/03/26/fedcoin-a-centrally-issued-alternative-to-peer-to-peer-currencies/>.
[^192]: Jean-Luc (Bitcoin.fr), *Naissance de l'Eurocoin*, 1 avril 2014 : <https://bitcoin.fr/naissance-de-l-eurocoin/>.
[^193]: John Paul Koning, *Fedcoin*, 19 octobre 2014 : <https://jpkoning.blogspot.com/2014/10/fedcoin.html>.
[^194]: David Andolfatto, *Fedcoin: On the Desirability of a Government Cryptocurrency*, 3 février 2015 : <https://andolfatto.blogspot.com/2015/02/fedcoin-on-desirability-of-government.html>.
[^195]: Ben Broadbent, *Central banks and digital currencies*, 2 mars 2016 : <https://www.bankofengland.co.uk/speech/2016/central-banks-and-digital-currencies>.
[^196]: Digital Currency Initiative, *About the MIT Digital Currency Initiative* : <https://dci.mit.edu/about>.
[^197]: James Lovejoy, Cory Fields, Madars Virza, Tyler Frederick, David Urness, Kevin Karwaski, Anders Brownworth, Neha Narula, *A High Performance Payment Processing System Designed for Central Bank Digital Currencies*, 3 février 2022 : <https://www.bostonfed.org/publications/one-time-pubs/project-hamilton-phase-1-executive-summary.aspx>.
[^198]: Fabio Panetta, *Demystifying wholesale central bank digital currency*, 26 septembre 2022 : <https://www.ecb.europa.eu/press/key/date/2022/html/ecb.sp220926~5f9b85685a.en.html>.
[^199]: Le point 5 du programme dressé dans le Manifeste du parti communiste prône la « centralisation du crédit entre les mains de l'État, au moyen d'une banque nationale, dont le capital appartiendra à l'État et qui jouira d'un monopole exclusif. » -- Karl Marx, *Manifeste du parti communiste*, Ère Nouvelle, 1895.
[^200]: Edward Snowden, *Your Money AND Your Life*, 9 octobre 2021 : <https://edwardsnowden.substack.com/p/cbdcs>.
[^201]: William Rees-Mogg, James Dale Davidson, *The Sovereign Individual: Mastering the Transition to the Information Age*, Touchstone, 1999, p. 247.
[^202]: John Perry Barlow, *A Declaration of the Independence of Cyberspace*, 8 février 1996 : <https://www.eff.org/fr/cyberspace-independence>.
[^203]: Kevin Kelly, « *E-Money* », in *Out of Control: The New Biology of Machines, Social Systems, and the Economic World*, Addison-Wesley, 1994 : <https://kk.org/mt-files/outofcontrol/ch12-f.html>.
[^204]: Cette dynamique a été formalisée par Parker Lewis sous la forme d'un dilemme du prisonnier appliqué à la question de l'interdiction de Bitcoin. Voir Parker Lewis, *Bitcoin Cannot be Banned*, 11 août 2019 : <https://unchained.com/blog/bitcoin-cannot-be-banned/>.
[^205]: Voir à ce sujet Hans-Hermann Hoppe, « *Banking, Nation States, and International Politics: A Sociological Reconstruction of the Present Economic Order* », in *The Review of Austrian Economics*, vol. 4, no. 3, 1990, pp. 55--87 : <https://mises.org/library/banking-nation-states-and-international-politics-sociological-reconstruction-present>.
[^206]: Cette loi du 8 juin 1864 est devenue la section 486 du titre 18 du Code des États-Unis (intitulée *18 U.S. Code § 486 - Uttering coins of gold, silver or other metal*) qui dispose : « Quiconque, sauf dans le cas où cela est autorisé par la loi, fabrique, met en circulation ou fait passer, ou tente de mettre en circulation ou de faire passer, des pièces d'or ou d'argent ou d'autres métaux, ou des alliages de métaux, destinées à être utilisées comme monnaie courante, qu'elles ressemblent à des pièces des États-Unis ou de pays étrangers, ou qu'elles soient de conception originale, sera condamné à une amende en vertu du présent titre ou à une peine d'emprisonnement de cinq ans au maximum, ou aux deux. »
[^207]: Wendy McElroy, « *Anthony L. Hargis And The Trusted Third Party Trap* », *Agorist Nexus*, 14 mai 2020 : <https://www.agoristnexus.com/anthony-l-hargis-and-the-trusted-third-party-trap/>.
[^208]: Samuel Edward Konkin [iii]{.smallcaps}, *Counter-Economics: From the Back Alleys\... To the Stars*, KoPubCo, 2018.
[^209]: P. Carl Mullan, *A History of Digital Currency in the United States*, Palgrave Macmillan, 2016.
[^210]: United States Mint, *Liberty Dollars Not Legal Tender, United States Mint Warns Consumers*, 14 septembre 2006 : <https://www.usmint.gov/news/press-releases/20060914-liberty-dollars-not-legal-tender-united-states-mint-warns-consumers>.
[^211]: Dustin Trammell, *The Problem With the Liberty Dollar*, 7 décembre 2008 : <https://blog.dustintrammell.com/the-problem-with-the-liberty-dollar/>.
[^212]: « Il est intéressant de noter que l'un des systèmes d'e-gold a déjà une forme de spam appelé "dusting". Les spammeurs envoient une minuscule quantité de poussière d'or afin de placer un message de spam dans le champ de commentaire de la transaction. » -- Satoshi Nakamoto, *Re: Bitcoin v0.1 released*, 25/01/2009 15:47:10 UTC : <https://www.metzdowd.com/pipermail/cryptography/2009-January/015041.html>.
[^213]: Correspondance par courriel entre Ross Ulbricht et Arto Bendiken (GX-270), septembre 2009 : <https://antilop.cc/sr/exhibits/253456462-Silk-Road-exhibits-GX-270.pdf>
[^214]: United States District Court for the Southern District of New York, *Liberty Reserve, et al. Indictment*, 28 mai 2013 : <https://www.justice.gov/sites/default/files/usao-sdny/legacy/2015/03/25/Liberty%20Reserve%2C%20et%20al.%20Indictment%20-%20Redacted_0.pdf>.
[^215]: Lawrence H. White, « *The Troubling Suppression of Competition from Alternative Monies: The Cases of the Liberty Dollar and E-Gold* », in *Cato Journal*, vol. 34, no. 2, 2014, pp. 281--301 : <https://ciaotest.cc.columbia.edu/journals/cato/v34i2/f_0031473_25521.pdf>.
[^216]: En particulier, la vision originelle de PayPal, produit développé par Confinity Inc. au tout début, était révolutionnaire. Voici quel était le discours de son PDG Peter Thiel à l'automne 1999, rapporté par Eric Jackson en 2012 : « Ce que nous qualifions de "pratique" pour les utilisateurs américains sera révolutionnaire pour les pays en développement. Les États de nombre de ces pays jouent avec leur monnaie. Ils ont recours à l'inflation et parfois à des dévaluations monétaires massives, comme nous l'avons vu en Russie et dans plusieurs pays d'Asie du Sud-Est l'année dernière, pour priver leurs citoyens de leurs richesses. La plupart des gens ordinaires n'ont jamais l'occasion d'ouvrir un compte à l'étranger ou de mettre la main sur plus de quelques billets d'une monnaie stable comme le dollar américain. Un jour, PayPal sera en mesure de changer cette situation. À l'avenir, lorsque notre service sera disponible en dehors des États-Unis et que la pénétration d'Internet continuera à s'étendre à tous les niveaux économiques, PayPal permettra aux citoyens du monde entier d'exercer un contrôle plus direct sur leurs monnaies qu'ils ne l'ont jamais fait auparavant. Il sera pratiquement impossible pour les États corrompus de voler les richesses de leurs citoyens par leurs anciens moyens, car, dans le cas où ils essaient, les citoyens se tourneront vers le dollar, la livre ou le yen, abandonnant ainsi leur monnaie locale sans valeur pour quelque chose de plus sûr. » -- Voir Eric M. Jackson, *The PayPal Wars: Battles With Ebay, the Media, the Mafia, and the Rest of Planet Earth*, World Ahead Pub., 2012.