# Ordinals

Cet ouvrage est lié à 21 jetons non fongibles (NFT) émis grâce au protocole Ordinals, dont les inscriptions ont pour identifiants :

1)  
2)  
3)  
4)  
5)  
6)  
7)  
8)  
9)  
10) 
11) 
12) 
13) 
14) 
15) 
16) 
17) 
18) 
19) 
20) 
21) 































































































































    Ross Ubricht a réitéré cette manœuvre sur le *Bitcoin Forum*, où il a écrit le 29 janvier : « Quelqu'un a-t-il déjà visité Silk Road ? C'est un peu comme un amazon.com anonyme. Je ne pense pas qu'il y ait de l'héroïne sur ce site, mais ils vendent d'autres choses. Ils utilisent essentiellement bitcoin et tor pour négocier des transactions anonymes. » -- Ross Ulbricht, *Re: A Heroin Store*, 29/01/2011 19:44:51 UTC, <https://bitcointalk.org/index.php?topic=175.msg42670#msg42670>.







































































































































































































































    Sera puni d'une amende de 3 750 € et d'un emprisonnement de six mois quiconque aura incité le public à refuser ou à retarder le paiement de l'impôt. »













    Lors de la rédaction de cette loi en août 1936, le franc avait perdu 80 % de sa valeur en or à la suite de la Grande Guerre et allait en perdre encore 30 % suite à la dévaluation du 25 septembre suivant.




































































































































































































































































     G = &~(~\mathtt{0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798}, \\&~\mathtt{0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8}~)~. 
    \end{aligned}$$ Il a pour ordre le nombre premier $$n = \mathtt{0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141}~,$$ de sorte que $n~G = 0$.





    -   Choisir aléatoirement une clé éphémère $l$ inférieure à $n-1$ ;

    -   Calculer les coordonnées $(i,j)$ du point $l~G$ ;

    -   Calculer $r = i \mod n$ ; si $r = 0$, choisir un autre $l$ ;

    -   Calculer $s = l^{-1} ( H(m) + k r ) \mod n$ ; si $s = 0$, choisir un autre $l$ ;

    -   La signature est $( r, s )$.

    L'algorithme de vérification est le suivant :

    -   Vérifier que $K \ne 0$ et que $K$ appartient à la courbe ;

    -   Vérifier que $n~K = 0$ ;

    -   Vérifier que $1 \leq r \leq n - 1$ et $1 \leq s \leq n - 1$ ;

    -   Calculer $(i, j) = ( H(m) s^{-1} \mod n )~G + ( r s^{-1} \mod n  )~K$ ;

    -   Vérifier que $r = i \mod n$.































































































































































































































    Cette préoccupation a conduit Hal Finney à écrire son troisième et dernier tweet sur Bitcoin où il affirmait réfléchir « à la manière de réduire les émissions de CO~2~ que produiraient une mise en œuvre généralisée de Bitcoin ». -- Hal Finney sur Twitter, 27/01/2009 20:14 UTC : <https://twitter.com/halfin/status/1153096538>.





















    Les alertes décrites par Satoshi sont aujourd'hui appelées preuves de fraude mais sont toujours en phase de développement.















    Une double dépense conséquente a été réalisée : macbook-air, *A successful DOUBLE SPEND US\$10000 against OKPAY this morning.*, 12/03/2013, 18:22:02 UTC : <https://bitcointalk.org/index.php?topic=152348.msg1616747#msg1616747>.





















































































































    $$S = r~V = r~v~G = v~r~G = v~R$$

    et la clé publique de réception est :

    $$P = K + H(S)~G~.$$

    Le destinataire peut aussi n'utiliser qu'une seule paire de clés $(k, K)$. Dans ce cas, $M = K$.

















































































    Elle a également été favorisée de manière plus conservatrice par Monero, qui possède une taille de bloc dynamique basée sur un mécanisme de pénalité pour compenser les *excès* par rapport à la normale. Voir SerHack, *Mastering Monero: The Future of Private Transactions*, Amazon KDP, 2018, pp. 136--139.